package com.five_corp.ad.internal;

import com.facebook.internal.FacebookRequestErrorClassification;
import com.five_corp.ad.FiveAdErrorCode;
import com.google.android.gms.auth.api.proxy.AuthApiStatusCodes;
import com.json.mediationsdk.logger.IronSourceError;
import com.json.mediationsdk.utils.IronSourceConstants;
import com.ogury.ad.OguryBidTokenErrorCode;
import com.ogury.ad.OguryShowErrorCode;
import com.pubmatic.sdk.nativead.POBNativeConstants;
import com.vungle.ads.internal.protos.Sdk;
import io.bidmachine.protobuf.EventTypeExtended;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Init of enum field 'd' uses external variables
	at jadx.core.dex.visitors.EnumVisitor.createEnumFieldByConstructor(EnumVisitor.java:485)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByField(EnumVisitor.java:399)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByWrappedInsn(EnumVisitor.java:364)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromFilledArray(EnumVisitor.java:349)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:284)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInvoke(EnumVisitor.java:315)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:288)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:153)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:102)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX INFO: loaded from: classes10.dex */
public final class p {
    public static final p A;
    public static final p A0;
    public static final p A1;
    public static final p A2;
    public static final p A3;
    public static final p A4;
    public static final p A5;
    public static final p A6;
    public static final p B;
    public static final p B0;
    public static final p B1;
    public static final p B2;
    public static final p B3;
    public static final p B4;
    public static final p B5;
    public static final p B6;
    public static final p C;
    public static final p C0;
    public static final p C1;
    public static final p C2;
    public static final p C3;
    public static final p C4;
    public static final p C5;
    public static final p C6;
    public static final p D;
    public static final p D0;
    public static final p D1;
    public static final p D2;
    public static final p D3;
    public static final p D4;
    public static final p D5;
    public static final p D6;
    public static final p E;
    public static final p E0;
    public static final p E1;
    public static final p E2;
    public static final p E3;
    public static final p E4;
    public static final p E5;
    public static final p E6;
    public static final p F;
    public static final p F0;
    public static final p F1;
    public static final p F2;
    public static final p F3;
    public static final p F4;
    public static final p F5;
    public static final p F6;
    public static final p G;
    public static final p G0;
    public static final p G1;
    public static final p G2;
    public static final p G3;
    public static final p G4;
    public static final p G5;
    public static final p G6;
    public static final p H;
    public static final p H0;
    public static final p H1;
    public static final p H2;
    public static final p H3;
    public static final p H4;
    public static final p H5;
    public static final p H6;
    public static final p I;
    public static final p I0;
    public static final p I1;
    public static final p I2;
    public static final p I3;
    public static final p I4;
    public static final p I5;
    public static final p I6;
    public static final p J;
    public static final p J0;
    public static final p J1;
    public static final p J2;
    public static final p J3;
    public static final p J4;
    public static final p J5;
    public static final p J6;
    public static final p K;
    public static final p K0;
    public static final p K1;
    public static final p K2;
    public static final p K3;
    public static final p K4;
    public static final p K5;
    public static final p K6;
    public static final p L;
    public static final p L0;
    public static final p L1;
    public static final p L2;
    public static final p L3;
    public static final p L4;
    public static final p L5;
    public static final p L6;
    public static final p M;
    public static final p M0;
    public static final p M1;
    public static final p M2;
    public static final p M3;
    public static final p M4;
    public static final p M5;
    public static final p M6;
    public static final p N;
    public static final p N0;
    public static final p N1;
    public static final p N2;
    public static final p N3;
    public static final p N4;
    public static final p N5;
    public static final p N6;
    public static final p O;
    public static final p O0;
    public static final p O1;
    public static final p O2;
    public static final p O3;
    public static final p O4;
    public static final p O5;
    public static final p O6;
    public static final p P;
    public static final p P0;
    public static final p P1;
    public static final p P2;
    public static final p P3;
    public static final p P4;
    public static final p P5;
    public static final p P6;
    public static final p Q;
    public static final p Q0;
    public static final p Q1;
    public static final p Q2;
    public static final p Q3;
    public static final p Q4;
    public static final p Q5;
    public static final p Q6;
    public static final p R;
    public static final p R0;
    public static final p R1;
    public static final p R2;
    public static final p R3;
    public static final p R4;
    public static final p R5;
    public static final p R6;
    public static final p S;
    public static final p S0;
    public static final p S1;
    public static final p S2;
    public static final p S3;
    public static final p S4;
    public static final p S5;
    public static final p S6;
    public static final p T;
    public static final p T0;
    public static final p T1;
    public static final p T2;
    public static final p T3;
    public static final p T4;
    public static final p T5;
    public static final p T6;
    public static final p U;
    public static final p U0;
    public static final p U1;
    public static final p U2;
    public static final p U3;
    public static final p U4;
    public static final p U5;
    public static final p U6;
    public static final p V;
    public static final p V0;
    public static final p V1;
    public static final p V2;
    public static final p V3;
    public static final p V4;
    public static final p V5;
    public static final p V6;
    public static final p W;
    public static final p W0;
    public static final p W1;
    public static final p W2;
    public static final p W3;
    public static final p W4;
    public static final p W5;
    public static final /* synthetic */ p[] W6;
    public static final p X;
    public static final p X0;
    public static final p X1;
    public static final p X2;
    public static final p X3;
    public static final p X4;
    public static final p X5;
    public static final p Y;
    public static final p Y0;
    public static final p Y1;
    public static final p Y2;
    public static final p Y3;
    public static final p Y4;
    public static final p Y5;
    public static final p Z;
    public static final p Z0;
    public static final p Z1;
    public static final p Z2;
    public static final p Z3;
    public static final p Z4;
    public static final p Z5;
    public static final p a0;
    public static final p a1;
    public static final p a2;
    public static final p a3;
    public static final p a4;
    public static final p a5;
    public static final p a6;
    public static final p b0;
    public static final p b1;
    public static final p b2;
    public static final p b3;
    public static final p b4;
    public static final p b5;
    public static final p b6;
    public static final p c0;
    public static final p c1;
    public static final p c2;
    public static final p c3;
    public static final p c4;
    public static final p c5;
    public static final p c6;
    public static final p d;
    public static final p d0;
    public static final p d1;
    public static final p d2;
    public static final p d3;
    public static final p d4;
    public static final p d5;
    public static final p d6;
    public static final p e;
    public static final p e0;
    public static final p e1;
    public static final p e2;
    public static final p e3;
    public static final p e4;
    public static final p e5;
    public static final p e6;
    public static final p f;
    public static final p f0;
    public static final p f1;
    public static final p f2;
    public static final p f3;
    public static final p f4;
    public static final p f5;
    public static final p f6;
    public static final p g;
    public static final p g0;
    public static final p g1;
    public static final p g2;
    public static final p g3;
    public static final p g4;
    public static final p g5;
    public static final p g6;
    public static final p h;
    public static final p h0;
    public static final p h1;
    public static final p h2;
    public static final p h3;
    public static final p h4;
    public static final p h5;
    public static final p h6;
    public static final p i;
    public static final p i0;
    public static final p i1;
    public static final p i2;
    public static final p i3;
    public static final p i4;
    public static final p i5;
    public static final p i6;
    public static final p j;
    public static final p j0;
    public static final p j1;
    public static final p j2;
    public static final p j3;
    public static final p j4;
    public static final p j5;
    public static final p j6;
    public static final p k;
    public static final p k0;
    public static final p k1;
    public static final p k2;
    public static final p k3;
    public static final p k4;
    public static final p k5;
    public static final p k6;
    public static final p l;
    public static final p l0;
    public static final p l1;
    public static final p l2;
    public static final p l3;
    public static final p l4;
    public static final p l5;
    public static final p l6;
    public static final p m;
    public static final p m0;
    public static final p m1;
    public static final p m2;
    public static final p m3;
    public static final p m4;
    public static final p m5;
    public static final p m6;
    public static final p n;
    public static final p n0;
    public static final p n1;
    public static final p n2;
    public static final p n3;
    public static final p n4;
    public static final p n5;
    public static final p n6;
    public static final p o;
    public static final p o0;
    public static final p o1;
    public static final p o2;
    public static final p o3;
    public static final p o4;
    public static final p o5;
    public static final p o6;
    public static final p p;
    public static final p p0;
    public static final p p1;
    public static final p p2;
    public static final p p3;
    public static final p p4;
    public static final p p5;
    public static final p p6;
    public static final p q;
    public static final p q0;
    public static final p q1;
    public static final p q2;
    public static final p q3;
    public static final p q4;
    public static final p q5;
    public static final p q6;
    public static final p r;
    public static final p r0;
    public static final p r1;
    public static final p r2;
    public static final p r3;
    public static final p r4;
    public static final p r5;
    public static final p r6;
    public static final p s;
    public static final p s0;
    public static final p s1;
    public static final p s2;
    public static final p s3;
    public static final p s4;
    public static final p s5;
    public static final p s6;
    public static final p t;
    public static final p t0;
    public static final p t1;
    public static final p t2;
    public static final p t3;
    public static final p t4;
    public static final p t5;
    public static final p t6;
    public static final p u;
    public static final p u0;
    public static final p u1;
    public static final p u2;
    public static final p u3;
    public static final p u4;
    public static final p u5;
    public static final p u6;
    public static final p v;
    public static final p v0;
    public static final p v1;
    public static final p v2;
    public static final p v3;
    public static final p v4;
    public static final p v5;
    public static final p v6;
    public static final p w;
    public static final p w0;
    public static final p w1;
    public static final p w2;
    public static final p w3;
    public static final p w4;
    public static final p w5;
    public static final p w6;
    public static final p x;
    public static final p x0;
    public static final p x1;
    public static final p x2;
    public static final p x3;
    public static final p x4;
    public static final p x5;
    public static final p x6;
    public static final p y;
    public static final p y0;
    public static final p y1;
    public static final p y2;
    public static final p y3;
    public static final p y4;
    public static final p y5;
    public static final p y6;
    public static final p z;
    public static final p z0;
    public static final p z1;
    public static final p z2;
    public static final p z3;
    public static final p z4;
    public static final p z5;
    public static final p z6;

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public final int f1518a;
    public final FiveAdErrorCode b;
    public final boolean c;

    static {
        FiveAdErrorCode fiveAdErrorCode = FiveAdErrorCode.INTERNAL_ERROR;
        d = new p("ASSERTION_ERROR", 0, 1, fiveAdErrorCode, false);
        FiveAdErrorCode fiveAdErrorCode2 = FiveAdErrorCode.BAD_APP_ID;
        e = new p("BAD_APP_ID", 1, 2, fiveAdErrorCode2, false);
        FiveAdErrorCode fiveAdErrorCode3 = FiveAdErrorCode.BAD_SLOT_ID;
        f = new p("BAD_SLOT_ID", 2, 3, fiveAdErrorCode3, false);
        g = new p("EMPTY", 3, 5, fiveAdErrorCode, false);
        FiveAdErrorCode fiveAdErrorCode4 = FiveAdErrorCode.NO_AD;
        h = new p("EMPTY_MEDIA_CONFIG", 4, 6, fiveAdErrorCode4, false);
        i = new p("HTML_CONTENT_ERROR", 5, 7, fiveAdErrorCode, false);
        j = new p("INITIALIZATION_ERROR_GENERAL", 6, 8, fiveAdErrorCode, false);
        k = new p("INITIALIZATION_ERROR_PLAY_SERVICE_VERSION", 7, 9, fiveAdErrorCode, false);
        l = new p("INITIALIZATION_ERROR_WEBVIEW", 8, 10, fiveAdErrorCode, false);
        FiveAdErrorCode fiveAdErrorCode5 = FiveAdErrorCode.INVALID_STATE;
        m = new p("INVALID_STATE", 9, 11, fiveAdErrorCode5, false);
        n = new p("MOVIE_PLAYER_ERROR", 10, 12, fiveAdErrorCode, true);
        FiveAdErrorCode fiveAdErrorCode6 = FiveAdErrorCode.NETWORK_ERROR;
        o = new p("MOVIE_PLAYER_ERROR_CONTENT_PLAYER", 11, 13, fiveAdErrorCode6, false);
        p = new p("NETWORK_CLIENT_ERROR", 12, 14, fiveAdErrorCode, true);
        q = new p("NETWORK_CONNECTION_ERROR", 13, 15, fiveAdErrorCode6, false);
        r = new p("NETWORK_RESPONSE_ERROR", 14, 16, fiveAdErrorCode, false);
        s = new p("NETWORK_SERVER_ERROR", 15, 17, fiveAdErrorCode, false);
        t = new p("NO_CACHED_AD", 16, 18, fiveAdErrorCode4, false);
        u = new p("NO_FILL", 17, 19, fiveAdErrorCode6, false);
        v = new p("STORAGE_BROKEN_FILE_ERROR", 18, 20, fiveAdErrorCode, true);
        FiveAdErrorCode fiveAdErrorCode7 = FiveAdErrorCode.STORAGE_ERROR;
        w = new p("STORAGE_ERROR", 19, 21, fiveAdErrorCode7, true);
        FiveAdErrorCode fiveAdErrorCode8 = FiveAdErrorCode.SUPPRESSED;
        x = new p("SUPPRESSED", 20, 22, fiveAdErrorCode8, false);
        y = new p("WEBVIEW_INVALID_REQUEST", 21, 24, fiveAdErrorCode, false);
        z = new p("WEBVIEW_INVALID_RESPONSE", 22, 25, fiveAdErrorCode, false);
        A = new p("MOVIE_FILE_PARSE_ERROR", 23, 26, fiveAdErrorCode, true);
        B = new p("NETWORK_INTERRUPTED_ERROR", 24, 27, fiveAdErrorCode6, false);
        C = new p("STORAGE_FILE_NOT_FOUND_ERROR", 25, 28, fiveAdErrorCode7, true);
        D = new p("NO_SELECTABLE_CACHED_AD", 26, 29, fiveAdErrorCode4, false);
        E = new p("SELECTED_CACHED_AD_NOT_FOUND", 27, 30, fiveAdErrorCode4, false);
        F = new p("NO_CACHED_AD_IN_AD_CHECK_TIME", 28, 31, fiveAdErrorCode4, false);
        G = new p("EMPTY_MEDIA_CONFIG_IN_AD_CHECK_TIME", 29, 32, fiveAdErrorCode4, false);
        H = new p("INITIALIZATION_ERROR_FAIL_TO_FETCH_PLAY_SERVICE_VERSION", 30, 33, fiveAdErrorCode, false);
        I = new p("INITIALIZATION_ERROR_UNSUPPORTED_PLAY_SERVICE_VERSION", 31, 34, fiveAdErrorCode, false);
        J = new p("BITMAP_FACTORY_DECODE_FAIL_INVALID_IMAGE", 32, 100, fiveAdErrorCode, true);
        FiveAdErrorCode fiveAdErrorCode9 = FiveAdErrorCode.PLAYER_ERROR;
        K = new p("BITMAP_FACTORY_DECODE_FAIL_OUT_OF_MEMORY_ERROR", 33, 101, fiveAdErrorCode9, false);
        L = new p("BITMAP_FACTORY_DECODE_FAIL_BYTE_ARRAY_INVALID_IMAGE", 34, 102, fiveAdErrorCode, true);
        M = new p("BITMAP_FACTORY_DECODE_FAIL_BYTE_ARRAY_OUT_OF_MEMORY_ERROR", 35, 103, fiveAdErrorCode9, false);
        N = new p("BITMAP_DECODER_LOCAL_CACHE_FILE_NOT_FOUND", 36, 104, fiveAdErrorCode9, false);
        O = new p("RESIZABLE_AD_IMAGE_VIEW_NO_MAIN_IMAGE", 37, 200, fiveAdErrorCode, true);
        P = new p("RESIZABLE_AD_IMAGE_VIEW_MAIN_IMAGE_CANNOT_READY", 38, 201, fiveAdErrorCode, false);
        Q = new p("AD_CHECK_ERROR_MEDIA_CONFIG_NOT_FOUND", 39, 300, fiveAdErrorCode4, false);
        R = new p("AD_CHECK_ERROR_SLOT_CONFIG_NOT_FOUND", 40, 301, fiveAdErrorCode3, false);
        S = new p("AD_CHECK_ERROR_SELECTED_CACHED_AD_NOT_FOUND", 41, 302, fiveAdErrorCode4, false);
        T = new p("AD_CHECK_ERROR_AD_CHECK_SERVER_RESPONDS_NOT_TO_SHOW_AD", 42, 303, fiveAdErrorCode4, false);
        U = new p("AD_CHECK_ERROR_SELECTED_CACHED_AD_CANNOT_BE_LOADED", 43, 304, fiveAdErrorCode, true);
        V = new p("AD_CHECK_ERROR_SELECTED_FRESH_AD_CANNOT_BE_LOADED", 44, 305, fiveAdErrorCode, true);
        W = new p("AD_CHECK_ERROR_AD_CHECK_RESPONSE_BAD_APP_ID", 45, 306, fiveAdErrorCode2, false);
        X = new p("AD_CHECK_ERROR_AD_CHECK_RESPONSE_NETWORK_SERVER_ERROR", 46, 307, fiveAdErrorCode, false);
        Y = new p("AD_CHECK_ERROR_AD_CHECK_RESPONSE_NETWORK_CLIENT_ERROR", 47, 308, fiveAdErrorCode, true);
        Z = new p("AD_CHECK_ERROR_AD_CHECK_RESPONSE_NETWORK_RESPONSE_ERROR", 48, 309, fiveAdErrorCode, false);
        a0 = new p("AD_CHECK_ERROR_AD_CHECK_RESPONSE_NO_FILL", 49, 310, fiveAdErrorCode6, false);
        b0 = new p("AD_CHECK_ERROR_AD_CHECK_RESPONSE_JSON_ERROR", 50, 311, fiveAdErrorCode, false);
        c0 = new p("AD_CHECK_ERROR_AD_CHECK_RESPONSE_UNKNOWN_ERROR", 51, 312, fiveAdErrorCode, false);
        d0 = new p("AD_CHECK_ERROR_FAIL_TO_GET_FRESH_AD_TOKEN", 52, 313, fiveAdErrorCode, false);
        e0 = new p("AD_CHECK_ERROR_SUPPRESSED", 53, 314, fiveAdErrorCode8, false);
        f0 = new p("AD_CHECK_ERROR_WIN_AD_LIST_EMPTY", 54, 315, fiveAdErrorCode4, false);
        g0 = new p("AD_CHECK_ERROR_LAST_CACHED_WIN_AD_NOT_FOUND", 55, 316, fiveAdErrorCode, false);
        h0 = new p("AD_CHECK_ERROR_LAST_FRESH_WIN_AD_NOT_LOADABLE", 56, 317, fiveAdErrorCode, false);
        i0 = new p("AD_CHECK_ERROR_LAST_CACHED_WIN_AD_EXCEED_NUM_MAX_LOAD", 57, 318, fiveAdErrorCode4, false);
        j0 = new p("FULL_CACHE_MOVIE_PLAYER_SURFACE_CREATE_DATA_EXCEPTION", 58, 400, fiveAdErrorCode, false);
        k0 = new p("FULL_CACHE_MOVIE_PLAYER_SURFACE_CREATE_STATE_EXCEPTION", 59, 401, fiveAdErrorCode9, false);
        l0 = new p("FULL_CACHE_MOVIE_PLAYER_MEDIA_PLAYER_EXCEPTION", 60, 402, fiveAdErrorCode9, false);
        m0 = new p("FULL_CACHE_MOVIE_PLAYER_ERROR_PREPARE_FAILED", 61, 403, fiveAdErrorCode9, false);
        n0 = new p("FULL_CACHE_MOVIE_PLAYER_USE_RELEASED_MEDIA_PLAYER", 62, 404, fiveAdErrorCode9, false);
        o0 = new p("FULL_CACHE_MOVIE_PLAYER_SURFACE_CREATE_SET_READABLE_FAILED", 63, 405, fiveAdErrorCode9, false);
        p0 = new p("AUDIO_PLAYER_ERROR_MEDIA_CODEC_CREATE_FAILED", 64, 500, fiveAdErrorCode, false);
        q0 = new p("AUDIO_PLAYER_ERROR_MEDIA_CODEC_CONFIGURE_FAILED", 65, 501, fiveAdErrorCode, false);
        r0 = new p("VIDEO_PLAYER_ERROR_MEDIA_CODEC_CREATE_FAILED", 66, 600, fiveAdErrorCode, false);
        s0 = new p("VIDEO_PLAYER_ERROR_MEDIA_CODEC_CONFIGURE_FAILED", 67, 601, fiveAdErrorCode, false);
        t0 = new p("PARTIAL_CACHE_MOVIE_PLAYER_ERROR_UNCAUGHT_EXCEPTION", 68, 700, fiveAdErrorCode, false);
        u0 = new p("PARTIAL_CACHE_MOVIE_PLAYER_ERROR_DATA_EXTRACTOR_ERROR", 69, 701, fiveAdErrorCode, false);
        v0 = new p("PARTIAL_CACHE_MOVIE_PLAYER_ERROR_PREPARE_FAILED", 70, 702, fiveAdErrorCode, false);
        w0 = new p("PARTIAL_CACHE_MOVIE_PLAYER_ERROR_RELEASE_FAILED", 71, 703, fiveAdErrorCode, false);
        x0 = new p("PARTIAL_CACHE_MOVIE_PLAYER_ERROR_VIDEO_PREFILL_FAILED", 72, 704, fiveAdErrorCode, false);
        y0 = new p("PARTIAL_CACHE_MOVIE_PLAYER_ERROR_VIDEO_PLAYER_UNCAUGHT_EXCEPTION", 73, 705, fiveAdErrorCode, false);
        z0 = new p("PARTIAL_CACHE_MOVIE_PLAYER_ERROR_AUDIO_PLAYER_UNCAUGHT_EXCEPTION", 74, 706, fiveAdErrorCode, false);
        A0 = new p("PARTIAL_CACHE_MOVIE_PLAYER_ERROR_CREATE_FAILED_LOOPER_UNAVAILABLE", 75, 707, fiveAdErrorCode, false);
        B0 = new p("PARTIAL_CACHE_MOVIE_PLAYER_ERROR_STALL_TIMEOUT", 76, IronSourceError.ERROR_NT_INSTANCE_LOAD_TIMEOUT, fiveAdErrorCode6, false);
        C0 = new p("ENUM_UNKNOWN_SOUND_STATE", 77, 800, fiveAdErrorCode, true);
        D0 = new p("ENUM_UNKNOWN_SDK_REDIRECT_TYPE", 78, EventTypeExtended.EVENT_TYPE_EXTENDED_BURL_VALUE, fiveAdErrorCode, true);
        E0 = new p("ENUM_UNKNOWN_SHOW_BUTTON_TYPE", 79, EventTypeExtended.EVENT_TYPE_EXTENDED_NURL_VALUE, fiveAdErrorCode, true);
        F0 = new p("ENUM_UNKNOWN_EFFECT_TYPE", 80, EventTypeExtended.EVENT_TYPE_EXTENDED_LURL_VALUE, fiveAdErrorCode, true);
        G0 = new p("ENUM_UNKNOWN_POSITION", 81, EventTypeExtended.EVENT_TYPE_EXTENDED_CUSTOM_VALUE, fiveAdErrorCode, true);
        H0 = new p("ENUM_UNKNOWN_CLICK_TYPE", 82, EventTypeExtended.EVENT_TYPE_EXTENDED_CUSTOM_LOSS_VALUE, fiveAdErrorCode, true);
        I0 = new p("ENUM_UNKNOWN_POST_MOVIE_EVENT_TYPE", 83, EventTypeExtended.EVENT_TYPE_EXTENDED_CUSTOM_WIN_VALUE, fiveAdErrorCode, true);
        J0 = new p("ENUM_UNKNOWN_POST_MOVIE_LAYOUT_TYPE", 84, 807, fiveAdErrorCode, true);
        K0 = new p("ENUM_UNKNOWN_EXIT_SOUND_CONFIG", 85, 808, fiveAdErrorCode, true);
        L0 = new p("ENUM_UNKNOWN_ENTER_SOUND_CONFIG", 86, 809, fiveAdErrorCode, true);
        M0 = new p("ENUM_UNKNOWN_ORIENTATION_TYPE", 87, 810, fiveAdErrorCode, true);
        N0 = new p("ENUM_UNKNOWN_VIDEO_CLICK_TYPE", 88, 811, fiveAdErrorCode, true);
        O0 = new p("ENUM_UNKNOWN_MID_TYPE", 89, 812, fiveAdErrorCode, true);
        P0 = new p("ENUM_UNKNOWN_BLANK_SPACE_CLICK_TYPE", 90, 813, fiveAdErrorCode, true);
        Q0 = new p("ENUM_UNKNOWN_ELEMENT_POSITION", 91, 814, fiveAdErrorCode, true);
        R0 = new p("ENUM_UNKNOWN_ELEMENT_DISPLAY_TYPE", 92, 815, fiveAdErrorCode, true);
        S0 = new p("ENUM_UNKNOWN_ELEMENT_OBJECT_TYPE", 93, 816, fiveAdErrorCode, true);
        T0 = new p("ENUM_UNKNOWN_SEEK_BAR_LEFT_ELEMENT_TYPE", 94, 817, fiveAdErrorCode, true);
        U0 = new p("ENUM_UNKNOWN_SEEK_BAR_RIGHT_ELEMENT_TYPE", 95, 818, fiveAdErrorCode, true);
        V0 = new p("ENUM_UNKNOWN_POST_TYPE", 96, 819, fiveAdErrorCode, true);
        W0 = new p("ENUM_UNKNOWN_EXTRA_TRACKING_EVENT_TYPE", 97, 820, fiveAdErrorCode, true);
        X0 = new p("ENUM_UNKNOWN_MOAT_TRACKING_START_TIMING", 98, 821, fiveAdErrorCode, true);
        Y0 = new p("ENUM_UNKNOWN_CTA_BUTTON_TYPE", 99, 822, fiveAdErrorCode, true);
        Z0 = new p("ENUM_UNKNOWN_PAYMENT_BEACON_TYPE", 100, 823, fiveAdErrorCode, true);
        a1 = new p("ENUM_UNKNOWN_MEASUREMENT_STRATEGY", 101, 824, fiveAdErrorCode, true);
        b1 = new p("ENUM_UNKNOWN_CREATIVE_TYPE", 102, 825, fiveAdErrorCode, true);
        c1 = new p("ENUM_UNKNOWN_MOVIE_PLAYER_TYPE", 103, 826, fiveAdErrorCode, true);
        d1 = new p("ENUM_UNKNOWN_CUSTOM_LAYOUT_CLICK_TYPE", 104, 827, fiveAdErrorCode, true);
        e1 = new p("ENUM_UNKNOWN_CUSTOM_LAYOUT_OBJECT_TYPE", 105, 828, fiveAdErrorCode, true);
        f1 = new p("ENUM_UNKNOWN_CUSTOM_LAYOUT_SOUND_CONDITION", 106, 829, fiveAdErrorCode, true);
        g1 = new p("ENUM_UNKNOWN_CUSTOM_LAYOUT_PLAYBACK_CONDITION", 107, 830, fiveAdErrorCode, true);
        h1 = new p("ENUM_UNKNOWN_TEXT_GRAVITY", 108, 831, fiveAdErrorCode, true);
        i1 = new p("ENUM_UNKNOWN_TIME_RANGE_TYPE", 109, 832, fiveAdErrorCode, true);
        j1 = new p("ENUM_UNKNOWN_SCREEN_MODE", 110, 833, fiveAdErrorCode, true);
        k1 = new p("ENUM_UNKNOWN_AD_CHECK_RESPONSE_TYPE", 111, 834, fiveAdErrorCode, true);
        l1 = new p("ENUM_UNKNOWN_BEACON_TYPE", 112, 835, fiveAdErrorCode, true);
        m1 = new p("ENUM_UNKNOWN_WEB_VIEW_SDK_MESSAGE_TYPE", 113, 836, fiveAdErrorCode, true);
        n1 = new p("ENUM_UNKNOWN_WEB_VIEW_SDK_SPECIFIED_MESSAGE_TYPE", 114, 837, fiveAdErrorCode, true);
        o1 = new p("ENUM_UNKNOWN_TIME_BEACON_TYPE", 115, 838, fiveAdErrorCode, true);
        p1 = new p("ENUM_UNKNOWN_EVENT_CLOCK_TYPE", 116, 839, fiveAdErrorCode, true);
        q1 = new p("ENUM_UNKNOWN_LIFETIME_TYPE", 117, 840, fiveAdErrorCode, true);
        r1 = new p("ENUM_UNKNOWN_MOVIE_SIZE_TYPE", Sdk.SDKError.Reason.PROTOBUF_SERIALIZATION_ERROR_VALUE, 841, fiveAdErrorCode, true);
        s1 = new p("ENUM_UNKNOWN_OPERATION_TYPE", Sdk.SDKError.Reason.JSON_ENCODE_ERROR_VALUE, 842, fiveAdErrorCode, true);
        t1 = new p("ENUM_UNKNOWN_OPEN_URL_REDIRECT_TYPE", 120, 843, fiveAdErrorCode, true);
        u1 = new p("ENUM_UNKNOWN_AD_FORMAT", Sdk.SDKError.Reason.TPAT_ERROR_VALUE, 844, fiveAdErrorCode, true);
        v1 = new p("ENUM_UNKNOWN_OM_TRACKING_EVENT_TYPE", Sdk.SDKError.Reason.INVALID_ADS_ENDPOINT_VALUE, 845, fiveAdErrorCode, true);
        w1 = new p("ENUM_UNKNOWN_OM_IMPRESSION_TYPE", Sdk.SDKError.Reason.INVALID_RI_ENDPOINT_VALUE, 846, fiveAdErrorCode, true);
        x1 = new p("ENUM_UNKNOWN_SHOW_AD_INFORMATION_TYPE", Sdk.SDKError.Reason.INVALID_LOG_ERROR_ENDPOINT_VALUE, 847, fiveAdErrorCode, true);
        y1 = new p("ENUM_UNKNOWN_FRIENDLY_OBSTRUCTION_TYPE", Sdk.SDKError.Reason.INVALID_METRICS_ENDPOINT_VALUE, 848, fiveAdErrorCode, true);
        z1 = new p("ENUM_UNKNOWN_VIEWABILITY_CALCULATION_MODE", 126, 849, fiveAdErrorCode, true);
        A1 = new p("ENUM_UNKNOWN_MOVIE_PLAYER_VERSION", 127, 850, fiveAdErrorCode, true);
        B1 = new p("ENUM_UNSUPPORT_MID_TYPE", 128, 851, fiveAdErrorCode, true);
        C1 = new p("ENUM_UNSUPPORT_POST_TYPE", 129, 852, fiveAdErrorCode, true);
        D1 = new p("ENUM_UNKNOWN_VIEWABILITY_CHECK_TARGET", 130, 853, fiveAdErrorCode, true);
        E1 = new p("ENUM_UNKNOWN_VIEWABILITY_DEBUG_MODE", Sdk.SDKError.Reason.MRAID_JS_WRITE_FAILED_VALUE, 854, fiveAdErrorCode, true);
        F1 = new p("ENUM_UNKNOWN_INFORMATION_ICON_CLICK_ACTION_TYPE", Sdk.SDKError.Reason.OMSDK_DOWNLOAD_JS_ERROR_VALUE, 855, fiveAdErrorCode, true);
        G1 = new p("ENUM_UNKNOWN_INFORMATION_ICON_CLICK_CHOICE_TYPE", Sdk.SDKError.Reason.OMSDK_JS_WRITE_FAILED_VALUE, 856, fiveAdErrorCode, true);
        H1 = new p("ENUM_UNKNOWN_REMOTE_LOG_LEVEL", 134, 857, fiveAdErrorCode, true);
        I1 = new p("BYTE_BUFFER_CHAIN_MOVE_POSITION_NO_DATA", 135, 900, fiveAdErrorCode, true);
        J1 = new p("BYTE_BUFFER_CHAIN_MOVE_POSITION_REQUESTED_POSITION_TOO_SMALL", 136, 901, fiveAdErrorCode, true);
        K1 = new p("BYTE_BUFFER_CHAIN_MOVE_POSITION_REQUESTED_POSITION_TOO_LARGE", Sdk.SDKError.Reason.TPAT_RETRY_FAILED_VALUE, 902, fiveAdErrorCode, true);
        L1 = new p("BYTE_BUFFER_CHAIN_APPEND_DISCONTINUITY", 138, 903, fiveAdErrorCode, true);
        M1 = new p("BYTE_BUFFER_CHAIN_GET_NO_ENOUGH_DATA", 139, 904, fiveAdErrorCode, true);
        N1 = new p("BYTE_BUFFER_CHAIN_FILL_NO_ENOUGH_DATA", IronSourceConstants.USING_CACHE_FOR_INIT_EVENT, 905, fiveAdErrorCode, true);
        O1 = new p("BYTE_BUFFER_CHAIN_MOVE_POSITION_BACKWARD", 141, 906, fiveAdErrorCode, true);
        P1 = new p("BYTE_BUFFER_CHAIN_GET_PRECONDITION_NOT_SATISFIED_QUEUE_EMPTY", 142, EventTypeExtended.EVENT_TYPE_EXTENDED_AD_UNIT_IMPRESSION_VALUE, fiveAdErrorCode, true);
        Q1 = new p("BYTE_BUFFER_CHAIN_GET_PRECONDITION_NOT_SATISFIED_RANGE_INVALID_POSITION", 143, EventTypeExtended.EVENT_TYPE_EXTENDED_AD_UNIT_WIN_VALUE, fiveAdErrorCode, true);
        R1 = new p("BYTE_BUFFER_CHAIN_GET_PRECONDITION_NOT_SATISFIED_RANGE_NO_ENOUGH_DATA", 144, EventTypeExtended.EVENT_TYPE_EXTENDED_AD_UNIT_LOSS_VALUE, fiveAdErrorCode, true);
        S1 = new p("BYTE_BUFFER_CHAIN_GET_NODE_UNEXPECTED_UNAVAILABLE", 145, EventTypeExtended.EVENT_TYPE_EXTENDED_AD_UNIT_PAID_VALUE, fiveAdErrorCode, true);
        T1 = new p("BYTE_BUFFER_CHAIN_GET_CALCULATED_COPY_RANGE_INVALID", POBNativeConstants.POB_NATIVE_MAIN_IMG_H, 911, fiveAdErrorCode, true);
        U1 = new p("BYTE_BUFFER_CHAIN_APPEND_NON_POSITIVE_SIZE", 147, 912, fiveAdErrorCode, true);
        V1 = new p("HTTP_URL_CONNECTION_MALFORMED_URL", 148, 1000, fiveAdErrorCode, true);
        W1 = new p("HTTP_URL_CONNECTION_OPEN_CONNECTION", 149, 1001, fiveAdErrorCode6, true);
        X1 = new p("HTTP_URL_CONNECTION_CONNECT_FAIL", 150, 1002, fiveAdErrorCode6, true);
        Y1 = new p("HTTP_URL_CONNECTION_CONNECT_TIMEOUT", 151, 1003, fiveAdErrorCode6, true);
        Z1 = new p("HTTP_URL_CONNECTION_GET_RESPONSE_CODE", 152, 1004, fiveAdErrorCode6, true);
        a2 = new p("HTTP_URL_CONNECTION_GET_INPUT_STREAM_IO_EXCEPTION", 153, 1005, fiveAdErrorCode, true);
        b2 = new p("HTTP_URL_CONNECTION_GET_INPUT_STREAM_OTHER_EXCEPTION", 154, 1016, fiveAdErrorCode, true);
        c2 = new p("HTTP_URL_CONNECTION_GET_INPUT_STREAM_TIMEOUT", 155, 1006, fiveAdErrorCode, true);
        d2 = new p("HTTP_URL_CONNECTION_READ_INPUT_STREAM_IO_EXCEPTION", 156, 1007, fiveAdErrorCode, true);
        e2 = new p("HTTP_URL_CONNECTION_READ_INPUT_STREAM_OTHER_EXCEPTION", 157, 1017, fiveAdErrorCode, true);
        f2 = new p("HTTP_URL_CONNECTION_CONNECT_FAIL_OTHER_EXCEPTION", 158, 1008, fiveAdErrorCode6, true);
        g2 = new p("HTTP_URL_CONNECTION_ILLEGAL_STATE_ON_INIT", 159, 1009, fiveAdErrorCode, true);
        h2 = new p("HTTP_URL_CONNECTION_ILLEGAL_PARAMETER", 160, 1010, fiveAdErrorCode, true);
        i2 = new p("HTTP_URL_CONNECTION_OUTPUT_STREAM_IO_EXCEPTION", 161, 1011, fiveAdErrorCode6, true);
        j2 = new p("HTTP_URL_CONNECTION_PROTOCOL_EXCEPTION", 162, 1012, fiveAdErrorCode, true);
        k2 = new p("HTTP_URL_CONNECTION_SECURITY_EXCEPTION", 163, 1013, fiveAdErrorCode, true);
        l2 = new p("HTTP_URL_CONNECTION_NULL_POINTER_EXCEPTION", 164, 1014, fiveAdErrorCode, true);
        m2 = new p("HTTP_URL_CONNECTION_FAILS_TO_OPEN_WITHOUT_EXCEPTION", 165, 1015, fiveAdErrorCode, true);
        n2 = new p("HTTP_DOWNLOAD_CLIENT_CONTENT_RANGE_WHOLE_LENGTH_UNAVAILABLE_FOR_416", 166, 1100, fiveAdErrorCode, true);
        o2 = new p("HTTP_DOWNLOAD_CLIENT_CONTENT_RANGE_START_POSITION_UNAVAILABLE_FOR_206", 167, 1101, fiveAdErrorCode, true);
        p2 = new p("HTTP_DOWNLOAD_CLIENT_CONTENT_RANGE_END_POSITION_UNAVAILABLE_FOR_206", 168, IronSourceConstants.RV_API_HAS_AVAILABILITY_FALSE, fiveAdErrorCode, true);
        q2 = new p("HTTP_DOWNLOAD_CLIENT_CONTENT_RANGE_WHOLE_LENGTH_UNAVAILABLE_FOR_206", 169, 1103, fiveAdErrorCode, true);
        r2 = new p("HTTP_DOWNLOAD_CLIENT_UNEXPECTED_RESPONSE_CODE_3XX", 170, IronSourceConstants.RV_CHECK_PLACEMENT_CAPPED, fiveAdErrorCode, true);
        s2 = new p("HTTP_DOWNLOAD_CLIENT_UNEXPECTED_RESPONSE_CODE_4XX", 171, 1105, fiveAdErrorCode, true);
        t2 = new p("HTTP_DOWNLOAD_CLIENT_UNEXPECTED_RESPONSE_CODE_5XX", 172, 1106, fiveAdErrorCode, true);
        u2 = new p("HTTP_DOWNLOAD_CLIENT_UNEXPECTED_RESPONSE_CODE", 173, 1107, fiveAdErrorCode, true);
        v2 = new p("FILE_READER_FILE_INPUT_STREAM_CONSTRUCT_ERROR", 174, 1200, fiveAdErrorCode, true);
        w2 = new p("FILE_READER_FILE_INPUT_STREAM_SKIP_ERROR", 175, 1201, fiveAdErrorCode, true);
        x2 = new p("FILE_READER_FILE_INPUT_STREAM_SKIP_EXCEED_THRESHOLD", 176, 1202, fiveAdErrorCode, true);
        y2 = new p("FILE_READER_FILE_INPUT_STREAM_READ_ERROR", 177, 1203, fiveAdErrorCode, true);
        z2 = new p("FILE_READER_READ_CLOSED_OR_BROKEN_READER", 178, IronSourceConstants.RV_INSTANCE_STARTED, fiveAdErrorCode, true);
        A2 = new p("FILE_READER_CLOSE_INPUT_STREAM_ERROR", 179, IronSourceConstants.RV_INSTANCE_ENDED, fiveAdErrorCode, true);
        B2 = new p("FILE_READER_READ_NEGATIVE_LENGTH", 180, 1206, fiveAdErrorCode, true);
        C2 = new p("FILE_READER_ALREADY_CLOSED", 181, IronSourceConstants.RV_INSTANCE_AVAILABILITY_TRUE, fiveAdErrorCode, false);
        D2 = new p("FILE_READER_READ_ERROR_FOR_TEST", 182, 1299, fiveAdErrorCode, false);
        E2 = new p("FILE_WRITER_FILE_OUTPUT_STREAM_CONSTRUCT_ERROR", 183, IronSourceConstants.RV_AUCTION_REQUEST, fiveAdErrorCode, true);
        F2 = new p("FILE_WRITER_FILE_OUTPUT_STREAM_TRUNCATE_ERROR", 184, 1301, fiveAdErrorCode, true);
        G2 = new p("FILE_WRITER_FILE_OUTPUT_STREAM_WRITE_ERROR", 185, IronSourceConstants.RV_AUCTION_SUCCESS, fiveAdErrorCode, true);
        H2 = new p("FILE_WRITER_WRITE_CLOSED_OR_BROKEN_WRITER", 186, IronSourceConstants.RV_AD_UNIT_CAPPED, fiveAdErrorCode, true);
        I2 = new p("FILE_WRITER_ALREADY_CLOSED", 187, 1304, fiveAdErrorCode, false);
        J2 = new p("AUXILIARY_RESOURCE_CACHE_DOWNLOADER_START_TWICE", 188, IronSourceConstants.RV_CAP_PLACEMENT, fiveAdErrorCode, true);
        K2 = new p("AUXILIARY_RESOURCE_CACHE_DISCONTINUOUS_RESPONSE_DATA", 189, IronSourceConstants.RV_CAP_SESSION, fiveAdErrorCode, true);
        L2 = new p("AUXILIARY_RESOURCE_CACHE_RECEIVE_DATA_UNEXPECTED_WRITER_CLOSE", FacebookRequestErrorClassification.EC_INVALID_TOKEN, 1402, fiveAdErrorCode, true);
        M2 = new p("AUXILIARY_RESOURCE_CACHE_RANGE_RESPONSE_ERROR_MISMATCH_DOWNLOADED_FILE_SIZE", 191, 1403, fiveAdErrorCode, true);
        N2 = new p("MOVIE_CACHE_PROGRESSIVE_DOWNLOADER_DISCONTINUOUS_RESPONSE_DATA", 192, 1500, fiveAdErrorCode, true);
        O2 = new p("MOVIE_CACHE_PROGRESSIVE_DOWNLOADER_RANGE_RESPONSE_ERROR_MISMATCH_DOWNLOADED_FILE_SIZE", 193, 1501, fiveAdErrorCode, true);
        P2 = new p("FIVE_DIRECTORY_FILE_LIST_FILES_EXCEPTION", 194, IronSourceConstants.RV_OPERATIONAL_LOAD_AD, fiveAdErrorCode, true);
        Q2 = new p("FIVE_DIRECTORY_FILE_EXISTS_EXCEPTION", 195, IronSourceConstants.RV_OPERATIONAL_LOAD_SUCCESS, fiveAdErrorCode, true);
        R2 = new p("FIVE_DIRECTORY_FILE_LENGTH_EXCEPTION", 196, IronSourceConstants.RV_OPERATIONAL_LOAD_FAILED, fiveAdErrorCode, true);
        S2 = new p("FIVE_DIRECTORY_FILE_DELETE_FAILED", 197, 1603, fiveAdErrorCode, true);
        T2 = new p("FIVE_DIRECTORY_FILE_DELETE_EXCEPTION", 198, 1604, fiveAdErrorCode, true);
        U2 = new p("FIVE_DIRECTORY_LOAD_DATA_SECURITY_EXCEPTION", 199, 1605, fiveAdErrorCode, true);
        V2 = new p("FIVE_DIRECTORY_LOAD_DATA_IO_EXCEPTION", 200, 1606, fiveAdErrorCode, true);
        W2 = new p("FIVE_DIRECTORY_LOAD_DATA_INPUT_STREAM_READ_EXCEED_THRESHOLD", 201, 1607, fiveAdErrorCode, true);
        X2 = new p("FIVE_DIRECTORY_LOAD_DATA_UNEXPECTED_EOF", 202, 1608, fiveAdErrorCode, true);
        Y2 = new p("FIVE_DIRECTORY_SAVE_DATA_SECURITY_EXCEPTION", 203, 1609, fiveAdErrorCode, true);
        Z2 = new p("FIVE_DIRECTORY_SAVE_DATA_IO_EXCEPTION", 204, 1610, fiveAdErrorCode, true);
        a3 = new p("FIVE_DIRECTORY_SAVE_DATA_SET_READABLE_FAILED", 205, 1611, fiveAdErrorCode, true);
        b3 = new p("FIVE_DIRECTORY_INITIALIZE_MKDIRS_FAILED", 206, 1612, fiveAdErrorCode, true);
        c3 = new p("FIVE_DIRECTORY_INITIALIZE_SET_READABLE_FAILED", 207, 1613, fiveAdErrorCode, true);
        d3 = new p("FIVE_DIRECTORY_INITIALIZE_SET_WRITABLE_FAILED", 208, 1614, fiveAdErrorCode, true);
        e3 = new p("FIVE_DIRECTORY_INITIALIZE_SET_EXECUTABLE_FAILED", 209, 1615, fiveAdErrorCode, true);
        f3 = new p("FIVE_DIRECTORY_INITIALIZE_SECURITY_EXCEPTION", 210, 1616, fiveAdErrorCode, true);
        g3 = new p("FIVE_DIRECTORY_SET_READABLE_FAILED", 211, 1617, fiveAdErrorCode, true);
        h3 = new p("FIVE_DIRECTORY_SET_READABLE_SECURITY_EXCEPTION", 212, 1618, fiveAdErrorCode, true);
        i3 = new p("FIVE_DIRECTORY_LOAD_DATA_OUT_OF_MEMORY", Sdk.SDKError.Reason.INVALID_ADUNIT_BID_PAYLOAD_VALUE, 1619, fiveAdErrorCode, false);
        j3 = new p("FIVE_DIRECTORY_GET_ABSOLUTE_PATH_FAILED", Sdk.SDKError.Reason.INVALID_GZIP_BID_PAYLOAD_VALUE, 1620, fiveAdErrorCode, true);
        k3 = new p("FIVE_DIRECTORY_SAVE_DATA_RENAME_FAILED", Sdk.SDKError.Reason.AD_RESPONSE_EMPTY_VALUE, 1621, fiveAdErrorCode, true);
        l3 = new p("FIVE_DIRECTORY_OPEN_INPUT_STREAM_FILE_NOT_FOUND", Sdk.SDKError.Reason.AD_RESPONSE_INVALID_TEMPLATE_TYPE_VALUE, 1622, fiveAdErrorCode, false);
        m3 = new p("FIVE_DIRECTORY_OPEN_OUTPUT_STREAM_FILE_NOT_FOUND", Sdk.SDKError.Reason.AD_RESPONSE_TIMED_OUT_VALUE, 1623, fiveAdErrorCode, false);
        n3 = new p("MOVIE_FILE_IO_MEDIATOR_PREPARE_REQUESTED_OFFSET_EXCEED_DOWNLOADED_LENGTH", Sdk.SDKError.Reason.MRAID_JS_DOES_NOT_EXIST_VALUE, 1700, fiveAdErrorCode, true);
        o3 = new p("MOVIE_FILE_IO_MEDIATOR_START_LOADING_CURRENT_OFFSET_EXCEED_DOWNLOADED_LENGTH", Sdk.SDKError.Reason.MRAID_JS_COPY_FAILED_VALUE, 1701, fiveAdErrorCode, true);
        p3 = new p("MOVIE_FILE_IO_MEDIATOR_RECEIVE_DATA_FROM_DISK_CURRENT_OFFSET_EXCEED_DOWNLOADED_LENGTH", Sdk.SDKError.Reason.AD_RESPONSE_RETRY_AFTER_VALUE, 1702, fiveAdErrorCode, true);
        q3 = new p("MOVIE_FILE_IO_MEDIATOR_SHOULD_LOAD_FROM_DISK_CURRENT_OFFSET_EXCEED_DOWNLOADED_LENGTH", Sdk.SDKError.Reason.AD_LOAD_FAIL_RETRY_AFTER_VALUE, 1703, fiveAdErrorCode, true);
        r3 = new p("MOVIE_FILE_IO_MEDIATOR_ON_DOWNLOAD_DATA_DOWNLOADED_FILE_LENGTH_MISMATCH", Sdk.SDKError.Reason.INVALID_WATERFALL_PLACEMENT_ID_VALUE, 1704, fiveAdErrorCode, true);
        s3 = new p("MOVIE_FILE_IO_MEDIATOR_ON_DOWNLOAD_DATA_CURRENT_OFFSET_MISMATCH", Sdk.SDKError.Reason.STALE_CACHED_RESPONSE_VALUE, 1705, fiveAdErrorCode, true);
        t3 = new p("MOVIE_FILE_IO_MEDIATOR_PREPARE_REQUESTED_OFFSET_EXCEED_DOWNLOADED_LENGTH_FULL_CACHED", 224, 1706, fiveAdErrorCode, true);
        u3 = new p("MOVIE_FILE_IO_MEDIATOR_PREPARE_REQUESTED_OFFSET_EXCEED_DOWNLOADED_LENGTH_NOT_FULL_CACHED", 225, 1707, fiveAdErrorCode, true);
        v3 = new p("MOVIE_FILE_IO_MEDIATOR_ON_DOWNLOAD_DATA_DOWNLOADED_FILE_LENGTH_NEGATIVE", 226, 1708, fiveAdErrorCode, true);
        w3 = new p("MOVIE_FILE_IO_MEDIATOR_RECEIVE_DATA_FROM_DISK_NEGATIVE_SIZE", 227, 1709, fiveAdErrorCode, true);
        x3 = new p("AD_CONFIG_SERIALIZE_EXCEPTION", 228, 1800, fiveAdErrorCode, false);
        y3 = new p("AD_CONFIG_DESERIALIZE_EXCEPTION", 229, 1801, fiveAdErrorCode, false);
        z3 = new p("AD_CONFIG_PARSE_TIMESTAMP_EXCEPTION", 230, 1802, fiveAdErrorCode, false);
        A3 = new p("AD_RESPONSE_PARSER_UNKNOWN_CUSTOM_LAYOUT_OBJECT_TYPE", 231, 1900, fiveAdErrorCode, true);
        B3 = new p("AD_RESPONSE_PARSER_INVALID_EXOPLAYER_CONFIG_INVALID_BUFFER_DURATION", 232, 1901, fiveAdErrorCode, true);
        C3 = new p("RESIZABLE_AD_VIDEO_VIEW_TAKE_SCREENSHOT_FAILED_NO_TEXTURE_VIEW", 233, 2000, fiveAdErrorCode, false);
        D3 = new p("RESIZABLE_AD_VIDEO_VIEW_TAKE_SCREENSHOT_FAILED_SURFACE_UNAVAILABLE", 234, 2001, fiveAdErrorCode, false);
        E3 = new p("RESIZABLE_AD_VIDEO_VIEW_TAKE_SCREENSHOT_FAILED_OUT_OF_MEMORY", 235, 2002, fiveAdErrorCode9, false);
        F3 = new p("RESIZABLE_AD_VIDEO_VIEW_TAKE_SCREENSHOT_FAILED_OTHER_EXCEPTION", 236, 2003, fiveAdErrorCode, false);
        G3 = new p("AD_CONTROLLER_LOADED_AD_UNAVAILABLE_PLAY_TIME_BEACON", 237, 2100, fiveAdErrorCode, false);
        H3 = new p("AD_CONTROLLER_LOADED_AD_UNAVAILABLE_DO_REDIRECT", 238, 2101, fiveAdErrorCode, false);
        I3 = new p("AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_CLOSE", 239, 2102, fiveAdErrorCode, false);
        J3 = new p("AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_IMPRESSION", 240, 2103, fiveAdErrorCode, false);
        K3 = new p("AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_VIEWABLE_IMPRESSION", 241, 2104, fiveAdErrorCode, false);
        L3 = new p("AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_VIDEO_START", 242, 2105, fiveAdErrorCode, false);
        M3 = new p("AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_PAUSE", 243, 2106, fiveAdErrorCode, false);
        N3 = new p("AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_RESUME", 244, 2107, fiveAdErrorCode, false);
        O3 = new p("AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_MOVIE_TIME_UPDATE", 245, 2108, fiveAdErrorCode, false);
        P3 = new p("AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_VIEW_THROUGH", 246, 2109, fiveAdErrorCode, false);
        Q3 = new p("AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_REPLAY", 247, 2110, fiveAdErrorCode, false);
        R3 = new p("AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_ANSWER", 248, IronSourceConstants.IS_CALLBACK_AD_SHOW_ERROR, fiveAdErrorCode, false);
        S3 = new p("AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_MOAT_TIME_BEACON", 249, IronSourceConstants.IS_CALLBACK_AD_DISPLAYED, fiveAdErrorCode, false);
        T3 = new p("AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_CLICK", 250, IronSourceConstants.IS_CALLBACK_AD_CLOSED, fiveAdErrorCode, false);
        U3 = new p("AD_CONTROLLER_GET_ACTIVITY_FAILED_WITH_EXCEPTION", 251, IronSourceConstants.IS_CALLBACK_AD_CLICKED, fiveAdErrorCode, false);
        V3 = new p("AD_CONTROLLER_GET_ACTIVITY_FAILED_WITHOUT_EXCEPTION", 252, IronSourceConstants.IS_CALLBACK_AD_INFO_CHANGED, fiveAdErrorCode, false);
        W3 = new p("AD_CONTROLLER_FAIL_TO_OPEN_APP_URL", 253, 2116, fiveAdErrorCode, false);
        X3 = new p("AD_CONTROLLER_UNEXPECTED_STATE_LOAD_AD", 254, 2117, fiveAdErrorCode5, false);
        Y3 = new p("AD_CONTROLLER_UNEXPECTED_STATE_ON_IMPRESSION", 255, 2118, fiveAdErrorCode5, false);
        Z3 = new p("AD_CONTROLLER_UNEXPECTED_STATE_ON_LOAD", 256, 2119, fiveAdErrorCode5, false);
        a4 = new p("AD_CONTROLLER_UNEXPECTED_STATE_ON_CLOSE", 257, 2120, fiveAdErrorCode5, false);
        b4 = new p("AD_CONTROLLER_AD_VIEW_UNAVAILABLE_SHOW_FULLSCREEN", 258, 2121, fiveAdErrorCode5, false);
        c4 = new p("AD_CONTROLLER_MAIN_ASSET_LOAD_TIMEOUT", 259, 2122, fiveAdErrorCode6, false);
        d4 = new p("AD_CONTROLLER_UNEXPECTED_STATE_SHOW_FULLSCREEN", 260, 2123, fiveAdErrorCode6, false);
        e4 = new p("AD_CONTROLLER_POST_EXIT_AFTER_REDIRECTING", 261, 2124, fiveAdErrorCode6, false);
        f4 = new p("AD_CONTROLLER_REDIRECT_AFTER_URL_CREATION", 262, 2125, fiveAdErrorCode6, false);
        g4 = new p("LEGACY_AD_CONTROLLER_LOADED_AD_UNAVAILABLE_PLAY_TIME_BEACON", 263, 2200, fiveAdErrorCode, false);
        h4 = new p("LEGACY_AD_CONTROLLER_LOADED_AD_UNAVAILABLE_DO_REDIRECT", 264, 2201, fiveAdErrorCode, false);
        i4 = new p("LEGACY_AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_CLOSE", 265, 2202, fiveAdErrorCode, false);
        j4 = new p("LEGACY_AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_IMPRESSION", 266, 2203, fiveAdErrorCode, false);
        k4 = new p("LEGACY_AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_VIEWABLE_IMPRESSION", 267, 2204, fiveAdErrorCode, false);
        l4 = new p("LEGACY_AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_VIDEO_START", 268, IronSourceConstants.IS_INSTANCE_INIT_SUCCESS, fiveAdErrorCode, false);
        m4 = new p("LEGACY_AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_PAUSE", 269, IronSourceConstants.IS_INSTANCE_INIT_FAILED, fiveAdErrorCode, false);
        n4 = new p("LEGACY_AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_RESUME", 270, 2207, fiveAdErrorCode, false);
        o4 = new p("LEGACY_AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_MOVIE_TIME_UPDATE", 271, 2208, fiveAdErrorCode, false);
        p4 = new p("LEGACY_AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_VIEW_THROUGH", 272, 2209, fiveAdErrorCode, false);
        q4 = new p("LEGACY_AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_REPLAY", 273, 2210, fiveAdErrorCode, false);
        r4 = new p("LEGACY_AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_ANSWER", 274, 2211, fiveAdErrorCode, false);
        s4 = new p("LEGACY_AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_MOAT_TIME_BEACON", 275, 2212, fiveAdErrorCode, false);
        t4 = new p("LEGACY_AD_CONTROLLER_LOADED_AD_UNAVAILABLE_ON_CLICK", 276, 2213, fiveAdErrorCode, false);
        u4 = new p("LEGACY_AD_CONTROLLER_UNEXPECTED_STATE_LOAD_AD", 277, 2214, fiveAdErrorCode5, false);
        v4 = new p("LEGACY_AD_CONTROLLER_UNEXPECTED_STATE_ON_IMPRESSION", POBNativeConstants.POB_NATIVE_MAIN_IMG_W, 2215, fiveAdErrorCode5, false);
        w4 = new p("LEGACY_AD_CONTROLLER_UNEXPECTED_STATE_ON_LOAD", 279, 2216, fiveAdErrorCode5, false);
        x4 = new p("LEGACY_AD_CONTROLLER_UNEXPECTED_STATE_ON_CLOSE", 280, 2217, fiveAdErrorCode5, false);
        y4 = new p("VIDEO_REWARD_CONTROLLER_NO_CONFIG", 281, 2300, fiveAdErrorCode4, false);
        z4 = new p("CUSTOM_LAYOUT_CONTROLLER_NO_CONFIG", 282, IronSourceConstants.IS_CAP_PLACEMENT, fiveAdErrorCode4, false);
        A4 = new p("CUSTOM_LAYOUT_CONTROLLER_HTML_ERROR", 283, IronSourceConstants.IS_CAP_SESSION, fiveAdErrorCode, false);
        B4 = new p("FIVE_AD_INFEED_NO_CONFIG", 284, 2500, fiveAdErrorCode4, false);
        C4 = new p("FIVE_AD_BOUNCE_NO_CONFIG", 285, IronSourceConstants.IS_OPERATIONAL_LOAD_AD, fiveAdErrorCode4, false);
        D4 = new p("FIVE_AD_W320_H180_NO_CONFIG", 286, 2700, fiveAdErrorCode4, false);
        E4 = new p("FIVE_AD_NATIVE_LOAD_ICON_IMAGE_NOT_YET_AD_LOADED", 287, 2800, fiveAdErrorCode, false);
        F4 = new p("FIVE_AD_NATIVE_LOAD_ICON_IMAGE_NO_ICON_IMAGE", 288, 2801, fiveAdErrorCode, false);
        G4 = new p("FIVE_AD_NATIVE_LOAD_INFORMATION_ICON_IMAGE_NOT_YET_AD_LOADED", 289, 2802, fiveAdErrorCode, false);
        H4 = new p("FIVE_AD_NATIVE_LOAD_INFORMATION_ICON_IMAGE_NO_INFORMATION_ICON_IMAGE", 290, 2803, fiveAdErrorCode, false);
        I4 = new p("FIVE_AD_NATIVE_CONFIG_HEIGHT_TO_WIDTH_RATIO_UNAVAILABLE", 291, 2804, fiveAdErrorCode, false);
        J4 = new p("MEDIA_USER_ATTRIBUTE_BROKEN_FILE", 292, 2900, fiveAdErrorCode, false);
        K4 = new p("MEDIA_CODEC_WRAPPER_SYNC_MEDIA_CODEC_CONFIGURE_FAILED", 293, 3000, fiveAdErrorCode9, false);
        L4 = new p("MEDIA_CODEC_WRAPPER_SYNC_MEDIA_CODEC_START_FAILED", 294, 3001, fiveAdErrorCode9, false);
        M4 = new p("MEDIA_CODEC_WRAPPER_SYNC_MEDIA_CODEC_DEQUEUE_INPUT_BUFFER", com.safedk.android.analytics.brandsafety.creatives.discoveries.l.h, 3002, fiveAdErrorCode, false);
        N4 = new p("MEDIA_CODEC_WRAPPER_SYNC_MEDIA_CODEC_GET_INPUT_BUFFER", com.safedk.android.analytics.brandsafety.creatives.discoveries.l.f, 3003, fiveAdErrorCode, false);
        O4 = new p("MEDIA_CODEC_WRAPPER_SYNC_MEDIA_CODEC_QUEUE_INPUT_BUFFER", 297, 3004, fiveAdErrorCode, false);
        P4 = new p("MEDIA_CODEC_WRAPPER_SYNC_MEDIA_CODEC_DEQUEUE_OUTPUT_BUFFER", 298, 3005, fiveAdErrorCode, false);
        Q4 = new p("MEDIA_CODEC_WRAPPER_SYNC_MEDIA_CODEC_GET_OUTPUT_BUFFER", 299, AuthApiStatusCodes.AUTH_APP_CERT_ERROR, fiveAdErrorCode, false);
        R4 = new p("MEDIA_CODEC_WRAPPER_SYNC_MEDIA_CODEC_RELEASE_OUTPUT_BUFFER", 300, IronSourceConstants.BN_INSTANCE_UNEXPECTED_LOAD_SUCCESS, fiveAdErrorCode, false);
        S4 = new p("MEDIA_CODEC_WRAPPER_SYNC_MEDIA_CODEC_STOP_FAILED", 301, 3008, fiveAdErrorCode, false);
        T4 = new p("MEDIA_CODEC_WRAPPER_SYNC_MEDIA_CODEC_GET_OUTPUT_FORMAT", 302, 3009, fiveAdErrorCode, false);
        U4 = new p("MEDIA_CODEC_WRAPPER_ASYNC_MEDIA_CODEC_CONFIGURE_FAILED", 303, 3100, fiveAdErrorCode9, false);
        V4 = new p("MEDIA_CODEC_WRAPPER_ASYNC_MEDIA_CODEC_START_FAILED", 304, 3101, fiveAdErrorCode9, false);
        W4 = new p("MEDIA_CODEC_WRAPPER_ASYNC_MEDIA_CODEC_ON_ERROR", 305, OguryShowErrorCode.AD_DISABLED_CONSENT_DENIED, fiveAdErrorCode, false);
        X4 = new p("MEDIA_CODEC_WRAPPER_ASYNC_MEDIA_CODEC_GET_INPUT_BUFFER", 306, OguryShowErrorCode.AD_DISABLED_CONSENT_MISSING, fiveAdErrorCode, false);
        Y4 = new p("MEDIA_CODEC_WRAPPER_ASYNC_MEDIA_CODEC_QUEUE_INPUT_BUFFER", 307, OguryShowErrorCode.AD_DISABLED_UNSPECIFIED_REASON, fiveAdErrorCode, false);
        Z4 = new p("MEDIA_CODEC_WRAPPER_ASYNC_MEDIA_CODEC_GET_OUTPUT_BUFFER", 308, 3105, fiveAdErrorCode, false);
        a5 = new p("MEDIA_CODEC_WRAPPER_ASYNC_MEDIA_CODEC_RELEASE_OUTPUT_BUFFER", 309, 3106, fiveAdErrorCode, false);
        b5 = new p("MEDIA_CODEC_WRAPPER_ASYNC_MEDIA_CODEC_STOP_FAILED", 310, 3107, fiveAdErrorCode, false);
        c5 = new p("AUDIO_SAMPLE_BUFFER_RENDERER_ERROR_MEDIA_CODEC_CREATE_FAILED", 311, 3200, fiveAdErrorCode, false);
        d5 = new p("AUDIO_SAMPLE_BUFFER_RENDERER_ON_ERROR", 312, 3201, fiveAdErrorCode, false);
        e5 = new p("AUDIO_TRACK_WRAPPER_SYNC_AUDIO_TRACK_CREATE_FAILED", 313, 3300, fiveAdErrorCode, false);
        f5 = new p("AUDIO_TRACK_WRAPPER_SYNC_AUDIO_TRACK_PLAY_FAILED", 314, IronSourceConstants.BN_INSTANCE_RELOAD_ERROR, fiveAdErrorCode, false);
        g5 = new p("AUDIO_TRACK_WRAPPER_SYNC_AUDIO_TRACK_STOP_FAILED", 315, IronSourceConstants.BN_INSTANCE_PRESENT_SCREEN, fiveAdErrorCode, false);
        h5 = new p("AUDIO_TRACK_WRAPPER_SYNC_AUDIO_TRACK_WRITE_ERROR_INVALID_OPERATION", 316, IronSourceConstants.BN_INSTANCE_DISMISS_SCREEN, fiveAdErrorCode, false);
        i5 = new p("AUDIO_TRACK_WRAPPER_SYNC_AUDIO_TRACK_WRITE_ERROR_DEAD_OBJECT", 317, 3304, fiveAdErrorCode, false);
        j5 = new p("AUDIO_TRACK_WRAPPER_SYNC_AUDIO_TRACK_WRITE_ERROR_BAD_VALUE", 318, 3305, fiveAdErrorCode, false);
        k5 = new p("AUDIO_TRACK_WRAPPER_SYNC_AUDIO_TRACK_WRITE_ERROR", Sdk.SDKError.Reason.SILENT_MODE_MONITOR_ERROR_VALUE, 3306, fiveAdErrorCode, false);
        l5 = new p("AUDIO_TRACK_WRAPPER_SYNC_AUDIO_TRACK_GET_MIN_BUFFER_SIZE_ERROR", 320, IronSourceConstants.BN_INSTANCE_RELOAD_NO_FILL, fiveAdErrorCode, false);
        m5 = new p("AUDIO_TRACK_WRAPPER_SYNC_AUDIO_TRACK_GET_MIN_BUFFER_SIZE_ERROR_BAD_VALUE", 321, IronSourceConstants.BN_INSTANCE_BOUND, fiveAdErrorCode, false);
        n5 = new p("AUDIO_TRACK_WRAPPER_SYNC_AUDIO_TRACK_SET_POSITION_NOTIFICATION_PERIOD_ERROR_INVALID_OPERATION", 322, 3309, fiveAdErrorCode, false);
        o5 = new p("PARTIAL_CACHE_MOVIE_PLAYER_DATA_MANAGER_UNCAUGHT_EXCEPTION", 323, IronSourceConstants.BN_PLACEMENT_CAPPED, fiveAdErrorCode, false);
        p5 = new p("PARTIAL_CACHE_MOVIE_PLAYER_DATA_MANAGER_RECEIVED_DATA_NON_POSITIVE_SIZE", 324, 3401, fiveAdErrorCode, false);
        q5 = new p("VIDEO_SAMPLE_BUFFER_RENDERER_ON_ERROR", 325, IronSourceConstants.BN_AUCTION_REQUEST, fiveAdErrorCode, false);
        r5 = new p("VIDEO_SAMPLE_BUFFER_RENDERER_QUEUE_INPUT_BUFFER", 326, IronSourceConstants.BN_AUCTION_FAILED, fiveAdErrorCode, false);
        s5 = new p("NET_UTIL_BYTE_ARRAY_OUTPUT_STREAM_FLUSH_EXCEPTION", 327, 3600, fiveAdErrorCode, false);
        t5 = new p("NET_UTIL_REDIRECT_URL_IS_MALFORMED", 328, 3601, fiveAdErrorCode, false);
        u5 = new p("OMID_METHOD_NOT_FOUND", 329, 3700, fiveAdErrorCode5, false);
        v5 = new p("OMID_RETURN_TYPE_CLASS_NOT_FOUND", 330, 3701, fiveAdErrorCode5, false);
        w5 = new p("OMID_METHOD_INVOCATION_EXCEPTION", 331, 3702, fiveAdErrorCode5, false);
        x5 = new p("OMID_ENUM_UNKNOWN_VALUE", 332, 3703, fiveAdErrorCode5, false);
        y5 = new p("OMID_JS_LIB_DOWNLOAD_FAILED", 333, 3704, fiveAdErrorCode, false);
        z5 = new p("OMID_VERIFICATION_URL_IS_MALFORMED", 334, 3705, fiveAdErrorCode, false);
        A5 = new p("OMID_SDK_NOT_FOUND", 335, 3706, fiveAdErrorCode, false);
        B5 = new p("OMID_SDK_IS_NOT_ACTIVE", 336, 3707, fiveAdErrorCode, false);
        C5 = new p("OMID_JS_LIB_NOT_FOUND", 337, 3708, fiveAdErrorCode, false);
        D5 = new p("OMID_PARTNER_OBJECT_NOT_FOUND", 338, 3709, fiveAdErrorCode, false);
        E5 = new p("OMID_UNSUPPORTED_IMPRESSION_TYPE", 339, 3710, fiveAdErrorCode, false);
        F5 = new p("OMID_UNSUPPORTED_CREATIVE_TYPE", 340, 3711, fiveAdErrorCode, false);
        G5 = new p("LOAD_AD_ERROR_NATIVE_API_IS_NOT_ALLOWED", FacebookRequestErrorClassification.EC_TOO_MANY_USER_ACTION_CALLS, 3800, fiveAdErrorCode5, false);
        H5 = new p("LOAD_AD_ERROR_FAIL_TO_GET_CONFIG_FROM_AD_TOKEN", 342, 3801, fiveAdErrorCode5, false);
        I5 = new p("LOAD_AD_ERROR_UNEXPECTED_CREATIVE_TYPE", 343, 3802, fiveAdErrorCode5, false);
        J5 = new p("LOAD_AD_ERROR_SIGNAL_COLLECT_TIMEOUT", 344, 3803, fiveAdErrorCode6, false);
        K5 = new p("LOAD_AD_ERROR_SIGNAL_STRING_JSON_ERROR", 345, 3804, fiveAdErrorCode, false);
        L5 = new p("LOAD_AD_ERROR_LOAD_ERROR_BID_RESPONSE_DECODE_ERROR", 346, 3805, fiveAdErrorCode6, false);
        M5 = new p("LOAD_AD_ERROR_LOAD_ERROR_BID_RESPONSE_PARSE_ERROR", 347, 3806, fiveAdErrorCode6, false);
        N5 = new p("LOAD_AD_ERROR_LOAD_ERROR_LOADED_AD_TOKEN_GENERATE_ERROR", 348, 3807, fiveAdErrorCode, false);
        O5 = new p("LOAD_AD_ERROR_LOAD_ERROR_BID_RESPONSE_AD_UNLOADABLE", 349, 3808, fiveAdErrorCode, false);
        P5 = new p("LOAD_AD_ERROR_RESOURCE_LOAD_TIMEOUT_ERROR", 350, 3809, fiveAdErrorCode6, false);
        Q5 = new p("LOAD_AD_ERROR_SIGNAL_COLLECT_NOT_DELIVERABLE_SLOT", 351, 3810, fiveAdErrorCode4, false);
        R5 = new p("LOCAL_CACHE_FILE_OPEN_FIVE_FILE_READER_ALREADY_DELETED", 352, 3900, fiveAdErrorCode5, false);
        S5 = new p("LOCAL_CACHE_FILE_OPEN_FIVE_FILE_WRITER_ALREADY_DELETED", 353, 3901, fiveAdErrorCode5, false);
        T5 = new p("LOCAL_CACHE_FILE_REQUEST_TO_WRITE_SUCCESS_FILE_ALREADY_DELETED", 354, 3902, fiveAdErrorCode5, false);
        U5 = new p("LOCAL_CACHE_FILE_REQUEST_TO_LOAD_ALL_DATA_ALREADY_DELETED", 355, 3903, fiveAdErrorCode5, false);
        V5 = new p("LOCAL_CACHE_FILE_REQUEST_TO_LOAD_ALL_DATA_DELETED_FIRST", 356, 3904, fiveAdErrorCode5, false);
        W5 = new p("LOCAL_CACHE_FILE_GET_IMAGE_RESOURCE_CACHE_ALREADY_DELETED", 357, 3905, fiveAdErrorCode5, false);
        X5 = new p("LOCAL_CACHE_FILE_GET_DOWNLOADED_FILE_SIZE_BYTE_ALREADY_DELETED", 358, 3906, fiveAdErrorCode5, false);
        Y5 = new p("LOCAL_CACHE_FILE_SET_READABLE_ALREADY_DELETED", 359, 3907, fiveAdErrorCode5, false);
        Z5 = new p("AD_REQUEST_SENDER_AD_REQUEST_BUILD_FAILED", 360, 4000, fiveAdErrorCode, false);
        a6 = new p("EXO_PLAYER_ERROR_CODE_AUDIO_TRACK_INIT_FAILED", 361, 4100, fiveAdErrorCode, false);
        b6 = new p("EXO_PLAYER_ERROR_CODE_AUDIO_TRACK_WRITE_FAILED", 362, OguryBidTokenErrorCode.AD_DISABLED_COUNTRY_NOT_OPENED, fiveAdErrorCode, false);
        c6 = new p("EXO_PLAYER_ERROR_CODE_BEHIND_LIVE_WINDOW", 363, OguryBidTokenErrorCode.AD_DISABLED_CONSENT_DENIED, fiveAdErrorCode, false);
        d6 = new p("EXO_PLAYER_ERROR_CODE_DECODER_INIT_FAILED", 364, OguryBidTokenErrorCode.AD_DISABLED_CONSENT_MISSING, fiveAdErrorCode, false);
        e6 = new p("EXO_PLAYER_ERROR_CODE_DECODER_QUERY_FAILED", 365, OguryBidTokenErrorCode.AD_DISABLED_UNSPECIFIED_REASON, fiveAdErrorCode, false);
        f6 = new p("EXO_PLAYER_ERROR_CODE_DECODING_FAILED", 366, 4105, fiveAdErrorCode, false);
        g6 = new p("EXO_PLAYER_ERROR_CODE_DECODING_FORMAT_EXCEEDS_CAPABILITIES", 367, 4106, fiveAdErrorCode, false);
        h6 = new p("EXO_PLAYER_ERROR_CODE_DECODING_FORMAT_UNSUPPORTED", 368, 4107, fiveAdErrorCode, false);
        i6 = new p("EXO_PLAYER_ERROR_CODE_DRM_CONTENT_ERROR", 369, 4108, fiveAdErrorCode, false);
        j6 = new p("EXO_PLAYER_ERROR_CODE_DRM_DEVICE_REVOKED", 370, 4109, fiveAdErrorCode, false);
        k6 = new p("EXO_PLAYER_ERROR_CODE_DRM_DISALLOWED_OPERATION", 371, IronSourceConstants.NT_CALLBACK_LOAD_SUCCESS, fiveAdErrorCode, false);
        l6 = new p("EXO_PLAYER_ERROR_CODE_DRM_LICENSE_ACQUISITION_FAILED", 372, IronSourceConstants.NT_CALLBACK_LOAD_ERROR, fiveAdErrorCode, false);
        m6 = new p("EXO_PLAYER_ERROR_CODE_DRM_LICENSE_EXPIRED", 373, IronSourceConstants.NT_CALLBACK_CLICK, fiveAdErrorCode, false);
        n6 = new p("EXO_PLAYER_ERROR_CODE_DRM_PROVISIONING_FAILED", 374, 4113, fiveAdErrorCode, false);
        o6 = new p("EXO_PLAYER_ERROR_CODE_DRM_SCHEME_UNSUPPORTED", 375, 4114, fiveAdErrorCode, false);
        p6 = new p("EXO_PLAYER_ERROR_CODE_DRM_SYSTEM_ERROR", 376, 4115, fiveAdErrorCode, false);
        q6 = new p("EXO_PLAYER_ERROR_CODE_DRM_UNSPECIFIED", 377, 4116, fiveAdErrorCode, false);
        r6 = new p("EXO_PLAYER_ERROR_CODE_FAILED_RUNTIME_CHECK", 378, 4117, fiveAdErrorCode, false);
        s6 = new p("EXO_PLAYER_ERROR_CODE_IO_BAD_HTTP_STATUS", 379, 4118, fiveAdErrorCode6, false);
        t6 = new p("EXO_PLAYER_ERROR_CODE_IO_CLEARTEXT_NOT_PERMITTED", 380, IronSourceConstants.NT_CALLBACK_SHOW, fiveAdErrorCode6, false);
        u6 = new p("EXO_PLAYER_ERROR_CODE_IO_FILE_NOT_FOUND", 381, 4120, fiveAdErrorCode6, false);
        v6 = new p("EXO_PLAYER_ERROR_CODE_IO_INVALID_HTTP_CONTENT_TYPE", 382, 4121, fiveAdErrorCode6, false);
        w6 = new p("EXO_PLAYER_ERROR_CODE_IO_NETWORK_CONNECTION_FAILED", 383, 4122, fiveAdErrorCode6, false);
        x6 = new p("EXO_PLAYER_ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT", 384, 4123, fiveAdErrorCode6, false);
        y6 = new p("EXO_PLAYER_ERROR_CODE_IO_NO_PERMISSION", 385, 4124, fiveAdErrorCode6, false);
        z6 = new p("EXO_PLAYER_ERROR_CODE_IO_READ_POSITION_OUT_OF_RANGE", 386, 4125, fiveAdErrorCode6, false);
        A6 = new p("EXO_PLAYER_ERROR_CODE_IO_UNSPECIFIED", 387, 4126, fiveAdErrorCode6, false);
        B6 = new p("EXO_PLAYER_ERROR_CODE_PARSING_CONTAINER_MALFORMED", 388, 4127, fiveAdErrorCode, true);
        C6 = new p("EXO_PLAYER_ERROR_CODE_PARSING_CONTAINER_UNSUPPORTED", 389, 4128, fiveAdErrorCode, true);
        D6 = new p("EXO_PLAYER_ERROR_CODE_PARSING_MANIFEST_MALFORMED", 390, 4129, fiveAdErrorCode, true);
        E6 = new p("EXO_PLAYER_ERROR_CODE_PARSING_MANIFEST_UNSUPPORTED", 391, 4130, fiveAdErrorCode, true);
        F6 = new p("EXO_PLAYER_ERROR_CODE_REMOTE_ERROR", 392, 4131, fiveAdErrorCode, false);
        G6 = new p("EXO_PLAYER_ERROR_CODE_TIMEOUT", 393, 4132, fiveAdErrorCode, false);
        H6 = new p("EXO_PLAYER_ERROR_CODE_UNSPECIFIED", 394, 4133, fiveAdErrorCode, false);
        I6 = new p("EXO_PLAYER_UNKNOWN_ERROR_CODE", 395, 4199, fiveAdErrorCode, false);
        J6 = new p("FIVE_EXO_PLAYER_ERROR_STALL_TIMEOUT", 396, 4200, fiveAdErrorCode6, false);
        K6 = new p("FIVE_EXO_PLAYER_ERROR_FULL_CACHE_PLAYER_NOT_IMPLEMENTED", 397, 4201, fiveAdErrorCode, false);
        L6 = new p("FIVE_EXO_PLAYER_ERROR_PARTIAL_CACHE_PLAYER_NOT_IMPLEMENTED", 398, 4202, fiveAdErrorCode, false);
        M6 = new p("AD_ACTIVITY_LAUNCHER_ALREADY_LAUNCHING", 399, IronSourceConstants.NT_INSTANCE_LOAD_ERROR, fiveAdErrorCode5, false);
        N6 = new p("AD_ACTIVITY_LAUNCHER_TIMEOUT", 400, 4301, fiveAdErrorCode, false);
        O6 = new p("AD_ACTIVITY_LAUNCHER_START_ACTIVITY_FAILED", 401, 4302, fiveAdErrorCode, false);
        P6 = new p("WEB_VIEW_HTML_PROMPT_VIEW_ON_RENDERER_PROCESS_GONE", 402, IronSourceConstants.NT_PLACEMENT_CAPPED, fiveAdErrorCode9, false);
        Q6 = new p("RESIZABLE_CUSTOM_LAYOUT_CREATE_ANIMATED_IMAGE", 403, IronSourceConstants.NT_AUCTION_REQUEST, fiveAdErrorCode, false);
        R6 = new p("RESIZABLE_FULL_SCREEN_SHOW_MID_VIEW", 404, 4600, fiveAdErrorCode, false);
        S6 = new p("RESIZABLE_FULL_SCREEN_SHOW_POST_VIEW", 405, 4601, fiveAdErrorCode, false);
        T6 = new p("AD_REPORT_DIALOG_ACTIVITY_LAUNCHER_ALREADY_LAUNCHING", 406, 4700, fiveAdErrorCode5, false);
        U6 = new p("AD_REPORT_DIALOG_ACTIVITY_LAUNCHER_TIMEOUT", 407, 4701, fiveAdErrorCode, false);
        V6 = new p("AD_REPORT_DIALOG_ACTIVITY_LAUNCHER_START_ACTIVITY_FAILED", 408, 4702, fiveAdErrorCode, false);
        W6 = a();
    }

    public p(String str, int i7, int i8, FiveAdErrorCode fiveAdErrorCode, boolean z7) {
        super(str, i7);
        this.f1518a = i8;
        this.b = fiveAdErrorCode;
        this.c = z7;
    }

    public static /* synthetic */ p[] a() {
        return new p[]{d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, a0, b0, c0, d0, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0, q0, r0, s0, t0, u0, v0, w0, x0, y0, z0, A0, B0, C0, D0, E0, F0, G0, H0, I0, J0, K0, L0, M0, N0, O0, P0, Q0, R0, S0, T0, U0, V0, W0, X0, Y0, Z0, a1, b1, c1, d1, e1, f1, g1, h1, i1, j1, k1, l1, m1, n1, o1, p1, q1, r1, s1, t1, u1, v1, w1, x1, y1, z1, A1, B1, C1, D1, E1, F1, G1, H1, I1, J1, K1, L1, M1, N1, O1, P1, Q1, R1, S1, T1, U1, V1, W1, X1, Y1, Z1, a2, b2, c2, d2, e2, f2, g2, h2, i2, j2, k2, l2, m2, n2, o2, p2, q2, r2, s2, t2, u2, v2, w2, x2, y2, z2, A2, B2, C2, D2, E2, F2, G2, H2, I2, J2, K2, L2, M2, N2, O2, P2, Q2, R2, S2, T2, U2, V2, W2, X2, Y2, Z2, a3, b3, c3, d3, e3, f3, g3, h3, i3, j3, k3, l3, m3, n3, o3, p3, q3, r3, s3, t3, u3, v3, w3, x3, y3, z3, A3, B3, C3, D3, E3, F3, G3, H3, I3, J3, K3, L3, M3, N3, O3, P3, Q3, R3, S3, T3, U3, V3, W3, X3, Y3, Z3, a4, b4, c4, d4, e4, f4, g4, h4, i4, j4, k4, l4, m4, n4, o4, p4, q4, r4, s4, t4, u4, v4, w4, x4, y4, z4, A4, B4, C4, D4, E4, F4, G4, H4, I4, J4, K4, L4, M4, N4, O4, P4, Q4, R4, S4, T4, U4, V4, W4, X4, Y4, Z4, a5, b5, c5, d5, e5, f5, g5, h5, i5, j5, k5, l5, m5, n5, o5, p5, q5, r5, s5, t5, u5, v5, w5, x5, y5, z5, A5, B5, C5, D5, E5, F5, G5, H5, I5, J5, K5, L5, M5, N5, O5, P5, Q5, R5, S5, T5, U5, V5, W5, X5, Y5, Z5, a6, b6, c6, d6, e6, f6, g6, h6, i6, j6, k6, l6, m6, n6, o6, p6, q6, r6, s6, t6, u6, v6, w6, x6, y6, z6, A6, B6, C6, D6, E6, F6, G6, H6, I6, J6, K6, L6, M6, N6, O6, P6, Q6, R6, S6, T6, U6, V6};
    }

    public static p valueOf(String str) {
        return (p) Enum.valueOf(p.class, str);
    }

    public static p[] values() {
        return (p[]) W6.clone();
    }
}
