package com.applovin.impl;

import com.applovin.impl.sdk.utils.JsonUtils;
import java.util.Arrays;
import java.util.concurrent.TimeUnit;

/* JADX INFO: loaded from: classes2.dex */
public abstract class o3 extends v4 {
    public static final v4 A7;
    public static final v4 B7;
    public static final v4 C7;
    public static final v4 D7;
    public static final v4 E7;
    public static final v4 F7;
    public static final v4 G7;
    public static final v4 H7;
    public static final v4 I7;
    public static final v4 J7;
    public static final v4 K7;
    public static final v4 L7;
    public static final v4 M7;
    public static final v4 N7;
    public static final v4 O7;
    public static final v4 P7;
    public static final v4 Q7;
    public static final v4 R7;
    public static final v4 S7;
    public static final v4 T7;
    public static final v4 U7;
    public static final v4 V7;
    public static final v4 W7;
    public static final v4 X7;
    public static final v4 Y7;
    public static final v4 Z7;
    public static final v4 a8;
    public static final v4 b8;
    public static final v4 c8;
    public static final v4 d7 = v4.a("afi", "");
    public static final v4 d8;
    public static final v4 e7;
    public static final v4 e8;
    public static final v4 f7;
    public static final v4 f8;
    public static final v4 g7;
    public static final v4 g8;
    public static final v4 h7;
    public static final v4 h8;
    public static final v4 i7;
    public static final v4 i8;
    public static final v4 j7;
    public static final v4 j8;
    public static final v4 k7;
    public static final v4 k8;
    public static final v4 l7;
    public static final v4 l8;
    public static final v4 m7;
    public static final v4 m8;
    public static final v4 n7;
    public static final v4 n8;
    public static final v4 o7;
    public static final v4 o8;
    public static final v4 p7;
    public static final v4 p8;
    public static final v4 q7;
    public static final v4 q8;
    public static final v4 r7;
    public static final v4 r8;
    public static final v4 s7;
    public static final v4 s8;
    public static final v4 t7;
    public static final v4 u7;
    public static final v4 v7;
    public static final v4 w7;
    public static final v4 x7;
    public static final v4 y7;
    public static final v4 z7;

    static {
        Boolean bool = Boolean.FALSE;
        e7 = v4.a("iafiwaa", bool);
        TimeUnit timeUnit = TimeUnit.SECONDS;
        f7 = v4.a("afi_ms", Long.valueOf(timeUnit.toMillis(5L)));
        g7 = v4.a("mediation_endpoint", "https://ms.applovin.com/");
        h7 = v4.a("mediation_backup_endpoint", "https://ms.applvn.com/");
        i7 = v4.a("fetch_next_ad_retry_delay_ms", Long.valueOf(timeUnit.toMillis(2L)));
        j7 = v4.a("fetch_next_ad_timeout_ms", Long.valueOf(timeUnit.toMillis(30L)));
        k7 = v4.a("fetch_mediation_debugger_info_timeout_ms", Long.valueOf(timeUnit.toMillis(7L)));
        Boolean bool2 = Boolean.TRUE;
        l7 = v4.a("auto_init_mediation_debugger", bool2);
        m7 = v4.a("postback_macros", "{\"{MCODE}\":\"mcode\",\"{BCODE}\":\"bcode\",\"{ICODE}\":\"icode\",\"{SCODE}\":\"scode\"}");
        n7 = v4.a("max_signal_provider_latency_ms", Long.valueOf(timeUnit.toMillis(30L)));
        o7 = v4.a("default_adapter_timeout_ms", Long.valueOf(timeUnit.toMillis(10L)));
        p7 = v4.a("ad_refresh_ms", Long.valueOf(timeUnit.toMillis(30L)));
        q7 = v4.a("ad_load_failure_refresh_ms", Long.valueOf(timeUnit.toMillis(30L)));
        r7 = v4.a("ad_load_failure_refresh_ignore_error_codes", "204");
        s7 = v4.a("refresh_ad_on_app_resume_elapsed_threshold_ms", 0L);
        t7 = v4.a("refresh_ad_view_timer_responds_to_background", bool2);
        u7 = v4.a("refresh_ad_view_timer_responds_to_store_kit", bool2);
        v7 = v4.a("refresh_ad_view_timer_responds_to_window_visibility_changed", bool);
        w7 = v4.a("avrsponse", bool);
        x7 = v4.a("allow_pause_auto_refresh_immediately", bool);
        y7 = v4.a("ad_view_race_condition_fix_enabled", bool);
        z7 = v4.a("always_destroy_ad_view_on_ui_thread", bool);
        A7 = v4.a("fullscreen_display_delay_ms", 0L);
        B7 = v4.a("susaode", bool);
        C7 = v4.a("ahdm", 500L);
        D7 = v4.a("ad_view_refresh_precache_request_viewability_undesired_flags", 246L);
        E7 = v4.a("ad_view_refresh_precache_request_enabled", bool2);
        F7 = v4.a("famttl_ms", 0L);
        G7 = v4.a("signal_expiration_ms", -1L);
        H7 = v4.a("signal_cache_level", Integer.valueOf(z4.b.AD_FORMAT.ordinal()));
        TimeUnit timeUnit2 = TimeUnit.HOURS;
        I7 = v4.a("ad_expiration_ms", Long.valueOf(timeUnit2.toMillis(4L)));
        J7 = v4.a("native_ad_expiration_ms", Long.valueOf(timeUnit2.toMillis(4L)));
        K7 = v4.a("rena", bool2);
        L7 = v4.a("fullscreen_ad_displayed_timeout_ms", -1L);
        M7 = v4.a("freast_ms", -1L);
        N7 = v4.a("ad_hidden_timeout_ms", -1L);
        O7 = v4.a("schedule_ad_hidden_on_ad_dismiss", bool);
        P7 = v4.a("schedule_ad_hidden_on_single_task_app_relaunch", bool);
        Q7 = v4.a("ad_hidden_on_ad_dismiss_callback_delay_ms", Long.valueOf(timeUnit.toMillis(1L)));
        R7 = v4.a("proe", bool);
        S7 = v4.a("mute_state", 2);
        T7 = v4.a("saf", "");
        U7 = v4.a("saui", "");
        V7 = v4.a("malm_v2_e", bool);
        W7 = v4.a("mspc", 1);
        X7 = v4.a("mra", -1);
        Y7 = v4.a("mra_af", "INTER,REWARDED,BANNER,LEADER,MREC");
        Z7 = v4.a("fadiafase", bool2);
        a8 = v4.a("fadwvcv", bool2);
        b8 = v4.a("bfarud", bool);
        c8 = v4.a("inacc", Boolean.valueOf(k7.b(Arrays.asList("com.textmeinc.textme", "com.textmeinc.freetone", "com.textmeinc.textme3", "com.jaumo", "com.jaumo.casual", "com.pinkapp", "com.jaumo.mature", "com.jaumo.prime", "com.jaumo.gay", "com.jaumo.lesbian"))));
        d8 = v4.a("adiets_sec", Long.valueOf(TimeUnit.MINUTES.toSeconds(1L)));
        e8 = v4.a("faomq", bool);
        f8 = v4.a("rahcnct_sec", -1);
        g8 = v4.a("paslbaf", JsonUtils.EMPTY_JSON);
        h8 = v4.a("msbl", "{\"ad\":[\"ttdasi_ms\"]}");
        i8 = v4.a("siarni", bool);
        j8 = v4.a("spims", bool);
        k8 = v4.a("uabta", bool);
        l8 = v4.a("use_initialization_spec_during_init", bool);
        m8 = v4.a("report_cimp_after_ierr", bool);
        n8 = v4.a("fail_collection_for_empty_signal", bool);
        o8 = v4.a("fetch_mediated_ad_gzip", bool2);
        p8 = v4.a("max_postback_gzip", bool2);
        q8 = v4.a("md_endpoint", "https://md.applovin.com/");
        r8 = v4.a("md_backup_endpoint", "https://md.applvn.com/");
        s8 = v4.a("md_v2", bool);
    }
}
