class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'game_title': 'CYBER NINJA',
      'play': 'PLAY',
      'mode_run': 'ENDLESS RUN',
      'mode_10x': '10X CHALLENGE',
      'mode_bird': 'CYBER JET SHINOBI',
      'mode_multiplayer': 'MULTIPLAYER RACE',
      'shop': 'SHOP',
      'settings': 'SETTINGS',
      'leaderboard': 'LEADERBOARD',
      'stats': 'STATISTICS',
      'gift_box': 'DAILY GIFT',
      'distance': 'DISTANCE',
      'best': 'BEST',
      'revive': 'REVIVE',
      'game_over': 'GAME OVER',
      'pause': 'PAUSED',
      'resume': 'RESUME',
      'restart': 'RESTART',
      'main_menu': 'MAIN MENU',
      'sound': 'SOUND EFFECTS',
      'music': 'MUSIC',
      'controls': 'CONTROLS',
      'booster_safe_ground': 'Safe Ground',
      'booster_matrix': 'Matrix Slow-Mo',
      'booster_invisibility': 'Invisibility',
      'booster_kill_eyes': 'Eye Killer',
      'cube_points': 'Cyber Points',
      'equipped': 'EQUIPPED',
      'equip': 'EQUIP',
      'unlock': 'UNLOCK',
    },
    'es': {
      'game_title': 'CYBER NINJA',
      'play': 'JUGAR',
      'mode_run': 'CARRERA SIN FIN',
      'mode_10x': 'DESAFÍO 10X',
      'mode_bird': 'VUELO CYBER SHINOBI',
      'mode_multiplayer': 'CARRERA MULTIJUGADOR',
      'shop': 'TIENDA',
      'settings': 'AJUSTES',
      'leaderboard': 'CLASIFICACIÓN',
      'stats': 'ESTADÍSTICAS',
      'gift_box': 'REGALO DIARIO',
      'distance': 'DISTANCIA',
      'best': 'RÉCORD',
      'revive': 'REVIVIR',
      'game_over': 'FIN DEL JUEGO',
      'pause': 'PAUSADO',
      'resume': 'REANUDAR',
      'restart': 'REINICIAR',
      'main_menu': 'MENÚ PRINCIPAL',
      'sound': 'EFECTOS DE SONIDO',
      'music': 'MÚSICA',
      'controls': 'CONTROLES',
      'booster_safe_ground': 'Suelo Seguro',
      'booster_matrix': 'Cámara Lenta',
      'booster_invisibility': 'Invisibilidad',
      'booster_kill_eyes': 'Destructor de Ojos',
      'cube_points': 'Puntos de Cubo',
      'equipped': 'EQUIPADO',
      'equip': 'EQUIPAR',
      'unlock': 'DESBLOQUEAR',
    },
    'ar': {
      'game_title': 'سايبر نينجا',
      'play': 'لعب',
      'mode_run': 'ركض لانهائي',
      'mode_10x': 'تحدي 10X',
      'mode_bird': 'طيران سايبر نينجا',
      'mode_multiplayer': 'سباق متعدد اللاعبين',
      'shop': 'المتجر',
      'settings': 'الإعدادات',
      'leaderboard': 'لوحة الصدارة',
      'stats': 'الإحصائيات',
      'gift_box': 'هدية يومية',
      'distance': 'المسافة',
      'best': 'الأفضل',
      'revive': 'إعادة إحياء',
      'game_over': 'انتهت اللعبة',
      'pause': 'مؤقت',
      'resume': 'استئناف',
      'restart': 'إعادة التشغيل',
      'main_menu': 'القائمة الرئيسية',
      'sound': 'المؤثرات الصوتية',
      'music': 'الموسيقى',
      'controls': 'التحكم',
      'booster_safe_ground': 'أرضية آمنة',
      'booster_matrix': 'حركة بطيئة',
      'booster_invisibility': 'اختفاء',
      'booster_kill_eyes': 'قاتل العيون',
      'cube_points': 'نقاط المكعب',
      'equipped': 'مستخدم',
      'equip': 'استخدام',
      'unlock': 'فتح',
    },
  };

  static String get(String key, [String lang = 'en']) {
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
