import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../storage/save_service.dart';

class LanguageInfo {
  final String code;
  final String nativeName;
  final String englishName;
  final String flag;

  const LanguageInfo({
    required this.code,
    required this.nativeName,
    required this.englishName,
    required this.flag,
  });
}

class AppLocalizations {
  final String languageCode;

  AppLocalizations(this.languageCode);

  static const List<LanguageInfo> supportedLanguages = [
    LanguageInfo(
      code: 'en',
      nativeName: 'English (US)',
      englishName: 'English',
      flag: '🇺🇸',
    ),
    LanguageInfo(
      code: 'hi',
      nativeName: 'हिन्दी',
      englishName: 'Hindi',
      flag: '🇮🇳',
    ),
    LanguageInfo(
      code: 'es',
      nativeName: 'Español',
      englishName: 'Spanish',
      flag: '🇪🇸',
    ),
    LanguageInfo(
      code: 'ja',
      nativeName: '日本語',
      englishName: 'Japanese',
      flag: '🇯🇵',
    ),
    LanguageInfo(
      code: 'fr',
      nativeName: 'Français',
      englishName: 'French',
      flag: '🇫🇷',
    ),
    LanguageInfo(
      code: 'de',
      nativeName: 'Deutsch',
      englishName: 'German',
      flag: '🇩🇪',
    ),
    LanguageInfo(
      code: 'ru',
      nativeName: 'Русский',
      englishName: 'Russian',
      flag: '🇷🇺',
    ),
    LanguageInfo(
      code: 'zh',
      nativeName: '简体中文',
      englishName: 'Chinese',
      flag: '🇨🇳',
    ),
    LanguageInfo(
      code: 'pt',
      nativeName: 'Português',
      englishName: 'Portuguese',
      flag: '🇧🇷',
    ),
    LanguageInfo(
      code: 'ar',
      nativeName: 'العربية',
      englishName: 'Arabic',
      flag: '🇸🇦',
    ),
    LanguageInfo(
      code: 'ko',
      nativeName: '한국어',
      englishName: 'Korean',
      flag: '🇰🇷',
    ),
    LanguageInfo(
      code: 'it',
      nativeName: 'Italiano',
      englishName: 'Italian',
      flag: '🇮🇹',
    ),
  ];

  static AppLocalizations of(BuildContext context) {
    final saveService = context.watch<SaveService>();
    return AppLocalizations(saveService.settings.languageCode);
  }

  // --- Translation Dictionary ---
  static const Map<String, Map<String, String>> _localizedValues = {
    // 1. English
    'en': {
      'game_title_cyber': 'CYBER',
      'game_title_runner': 'NINJA',
      'game_protocol': 'SHADOW & STEEL // PROTOCOL V2.5',
      'active_operative': 'ACTIVE OPERATIVE // SHADOW SHINOBI',
      'deployed': 'DEPLOYED',
      'settings': 'SETTINGS',
      'audio_settings': 'AUDIO SETTINGS',
      'music_volume': 'Music Volume',
      'sfx_volume': 'SFX Volume',
      'control_preferences': 'CONTROL PREFERENCES',
      'control_scheme': 'Control Scheme',
      'virtual_buttons': 'Virtual Buttons',
      'swipe_gestures': 'Swipe Gestures',
      'swipe_sensitivity': 'Swipe Sensitivity',
      'language': 'LANGUAGE',
      'app_language': 'App Language',
      'reset_data': 'RESET DATA & PROGRESS',
      'reset_warning':
          'This will reset all unlocked skins, high scores, and stats.',
      'reset_button': 'RESET ALL DATA',
      'daily_crate': 'DAILY CRATE',
      'daily_claimed': 'Claimed today! Next in',
      'daily_available': 'Daily reward claimed: +150 CP!',
      'arsenal_hangar': 'ARSENAL & HANGAR',
      'hall_of_fame': 'HALL OF FAME',
      'global_rankings': 'GLOBAL SHADOW DIVISION // ELITE AGENTS',
      'rank': 'RANK',
      'operative': 'OPERATIVE',
      'sector_record': 'SECTOR RECORD',
      'trophies': 'TROPHIES',
      'core_campaign': 'CORE CAMPAIGN',
      'extreme_risk': 'EXTREME RISK',
      'aerial_zero_g': 'AERIAL ZERO-G',
      'endless_title': 'ENDLESS OVERDRIVE',
      'endless_obj': 'Survive deep matrix sectors & defeat mechs',
      'endless_map': 'MAP: NEO-TOKYO MATRIX',
      'endless_sector': 'SECTOR 01-05 (200M CYCLING)',
      'tenx_title': '10X HYPER RUN',
      'tenx_obj': 'Hyperspeed survival with massive CP rewards',
      'tenx_map': 'MAP: OVERCHARGED FORGE',
      'tenx_sector': 'REACTOR CORE // 2X VELOCITY',
      'flight_title': 'JET SHINOBI FLIGHT',
      'flight_obj': 'Anti-gravity thrusters • Dodge laser webs',
      'flight_map': 'MAP: STRATOSPHERE SKYWAY',
      'flight_sector': 'SECTOR SKY-07 // FLIGHT VECTOR',
      'threat_lvl_3': 'THREAT: LVL 3 // MEDIUM',
      'threat_lvl_5': 'THREAT: LVL 5 // LETHAL',
      'threat_lvl_4': 'THREAT: LVL 4 // ELEVATED',
      'hazards_label': 'HAZARDS:',
      'best_record': 'BEST RECORD:',
      'equip': 'EQUIP',
      'equipped': 'EQUIPPED',
      'buy': 'BUY',
      'locked': 'LOCKED',
      'tab_operatives': 'OPERATIVES',
      'tab_drones': 'SHINOBI DRONES',
      'tab_boosters': 'BOOSTERS',
      'tactical_pause': 'TACTICAL PAUSE',
      'sys_frozen': 'SYS_STATE // FROZEN',
      'resume': 'RESUME MISSION',
      'restart': 'RESTART SECTOR',
      'abort': 'ABORT MISSION',
      'mission_failed': 'MISSION FAILED',
      'distance_reached': 'DISTANCE REACHED',
      'cp_harvested': 'CP HARVESTED',
      'deploy_again': 'DEPLOY AGAIN',
      'exit_hub': 'EXIT TO HUB',
      'section_armory': 'OPERATIVE ARMORY',
      'armory_title': 'CYBER NINJA CHASSIS & SKINS',
      'armory_desc': '// HIGH-TECH COMBAT SUITS & NEON AURA',
      'section_modules': 'TACTICAL MODULES',
      'modules_title': 'COMBAT OVERCLOCK BOOSTERS',
      'modules_desc': '// DEPLOYABLE MISSION CONSUMABLES',
      'section_protocols': 'NEURAL PROTOCOLS',
      'protocols_title': 'OPERATIVE AUGMENTS & ACCESS',
      'protocols_desc': '// PERMANENT SYSTEM OVERRIDES & MULTIPLIERS',
      'section_vault': 'DATA VAULT',
      'vault_title': 'CYBER POINT (CP) RECHARGE',
      'vault_desc': '// INSTANT QUANTUM CP TRANSFERS',
    },

    // 2. Hindi
    'hi': {
      'game_title_cyber': 'साइबर',
      'game_title_runner': 'निंजा',
      'game_protocol': 'शैडो और स्टील // प्रोटोकॉल V2.5',
      'active_operative': 'सक्रिय ऑपरेटिव // शैडो शिनोबी',
      'deployed': 'तैनात',
      'settings': 'सेटिंग्स',
      'audio_settings': 'ऑडियो सेटिंग्स',
      'music_volume': 'म्यूजिक वॉल्यूम',
      'sfx_volume': 'ध्वनि प्रभाव (SFX)',
      'control_preferences': 'नियंत्रण प्राथमिकताएं',
      'control_scheme': 'नियंत्रण मोड',
      'virtual_buttons': 'वर्चुअल बटन',
      'swipe_gestures': 'स्वाइप जेस्चर',
      'swipe_sensitivity': 'स्वाइप संवेदनशीलता',
      'language': 'भाषा (LANGUAGE)',
      'app_language': 'ऐप भाषा',
      'reset_data': 'डेटा और प्रगति रीसेट करें',
      'reset_warning':
          'यह सभी अनलॉक स्किन्स, हाई स्कोर और आंकड़े रीसेट कर देगा।',
      'reset_button': 'सभी डेटा रीसेट करें',
      'daily_crate': 'दैनिक क्रेट',
      'daily_claimed': 'आज ले लिया गया! अगला उपलब्ध होगा:',
      'daily_available': 'दैनिक इनाम प्राप्त: +150 CP!',
      'arsenal_hangar': 'शस्त्रागार और हैंगर',
      'hall_of_fame': 'हॉल ऑफ फेम',
      'global_rankings': 'वैश्विक शैडो डिवीजन // शीर्ष एजेंट्स',
      'rank': 'रैंक',
      'operative': 'ऑपरेटिव',
      'sector_record': 'सेक्टर रिकॉर्ड',
      'trophies': 'ट्रॉफियां',
      'core_campaign': 'मुख्य अभियान',
      'extreme_risk': 'अत्यधिक जोखिम',
      'aerial_zero_g': 'शून्य-गुरुत्वाकर्षण उड़ान',
      'endless_title': 'एंडलेस ओवरड्राइव',
      'endless_obj': 'गहन मैट्रिक्स में जीवित रहें और रोबोट्स को मात दें',
      'endless_map': 'मानचित्र: नियो-टोक्यो मैट्रिक्स',
      'endless_sector': 'सेक्टर 01-05 (200M चक्र)',
      'tenx_title': '10X हाइपर रन',
      'tenx_obj': 'तेज गति और भारी 10x CP पुरस्कार',
      'tenx_map': 'मानचित्र: ओवरचार्ज्ड फोर्ज',
      'tenx_sector': 'रिएक्टर कोर // 2X गति',
      'flight_title': 'जेट शिनोबी फ्लाइट',
      'flight_obj': 'थ्रस्टर्स से उड़ें • लेजर जालों से बचें',
      'flight_map': 'मानचित्र: समताप मंडल स्काईवे',
      'flight_sector': 'सेक्टर स्काई-07 // फ्लाइट वेक्टर',
      'threat_lvl_3': 'खतरा: स्तर 3 // मध्यम',
      'threat_lvl_5': 'खतरा: स्तर 5 // घातक',
      'threat_lvl_4': 'खतरा: स्तर 4 // उच्च',
      'hazards_label': 'खतरे:',
      'best_record': 'सर्वश्रेष्ठ रिकॉर्ड:',
      'equip': 'सुसज्जित करें',
      'equipped': 'सुसज्जित',
      'buy': 'खरीदें',
      'locked': 'बंद (LOCKED)',
      'tab_operatives': 'ऑपरेटिव्स',
      'tab_drones': 'शिनोबी ड्रोन्स',
      'tab_boosters': 'बूस्टर्स',
      'tactical_pause': 'सामरिक ठहराव (PAUSE)',
      'sys_frozen': 'सिस्टम // रुका हुआ',
      'resume': 'मिशन जारी रखें',
      'restart': 'सेक्टर पुनः शुरू करें',
      'abort': 'मिशन रद्द करें',
      'mission_failed': 'मिशन असफल',
      'distance_reached': 'तय की गई दूरी',
      'cp_harvested': 'अर्जित CP',
      'deploy_again': 'पुनः शुरू करें',
      'exit_hub': 'मुख्य मेन्यू पर जाएं',
      'section_armory': 'ऑपरेटिव आर्मरी',
      'armory_title': 'साइबर निंजा चेसिस और स्किन्स',
      'armory_desc': '// हाई-टेक कॉम्बैट सूट्स और ऑरा',
      'section_modules': 'टैक्टिकल मॉड्यूल्स',
      'modules_title': 'कॉम्बैट ओवरक्लॉक बूस्टर्स',
      'modules_desc': '// मिशन उपयोगी कॉम्बैट बूस्टर्स',
      'section_protocols': 'न्यूरल प्रोटोकॉल्स',
      'protocols_title': 'कोर ऑपरेटिव ऑग्मेंट्स',
      'protocols_desc': '// स्थायी वीआईपी विशेषाधिकार व गुणक',
      'section_vault': 'डेटा वॉल्ट',
      'vault_title': 'साइबर पॉइंट (CP) रिचार्ज',
      'vault_desc': '// त्वरित क्वांटम CP ट्रांसफ़र',
    },

    // 3. Spanish
    'es': {
      'game_title_cyber': 'CYBER',
      'game_title_runner': 'NINJA',
      'game_protocol': 'SOMBRA Y ACERO // PROTOCOLO V2.5',
      'active_operative': 'OPERATIVO ACTIVO // SHINOBI SOMBRA',
      'deployed': 'DESPLEGADO',
      'settings': 'AJUSTES',
      'audio_settings': 'AJUSTES DE AUDIO',
      'music_volume': 'Volumen de Música',
      'sfx_volume': 'Efectos de Sonido (SFX)',
      'control_preferences': 'PREFERENCIAS DE CONTROL',
      'control_scheme': 'Esquema de Control',
      'virtual_buttons': 'Botones Virtuales',
      'swipe_gestures': 'Gestos de Deslizar',
      'swipe_sensitivity': 'Sensibilidad de Deslizar',
      'language': 'IDIOMA',
      'app_language': 'Idioma de la App',
      'reset_data': 'REINICIAR DATOS Y PROGRESO',
      'reset_warning':
          'Esto reiniciará todos los trajes, récords y estadísticas.',
      'reset_button': 'REINICIAR TODOS LOS DATOS',
      'daily_crate': 'CAJA DIARIA',
      'daily_claimed': '¡Reclamado hoy! Siguiente en',
      'daily_available': '¡Recompensa diaria obtenida: +150 CP!',
      'arsenal_hangar': 'ARSENAL Y HANGAR',
      'hall_of_fame': 'SALÓN DE LA FAMA',
      'global_rankings': 'DIVISIÓN SOMBRA GLOBAL // AGENTES ÉLITE',
      'rank': 'RANGO',
      'operative': 'OPERATIVO',
      'sector_record': 'RÉCORD SECTOR',
      'trophies': 'TROFEOS',
      'core_campaign': 'CAMPAÑA PRINCIPAL',
      'extreme_risk': 'RIESGO EXTREMO',
      'aerial_zero_g': 'VUELO CERO-G',
      'endless_title': 'SOBREMARCHA INFINITA',
      'endless_obj': 'Sobrevive a sectores de la matriz y vence mechas',
      'endless_map': 'MAPA: MATRIZ NEO-TOKIO',
      'endless_sector': 'SECTOR 01-05 (CICLOS DE 200M)',
      'tenx_title': 'CARRERA HIPER 10X',
      'tenx_obj': 'Supervivencia a hipervelocidad con 10x recompensas',
      'tenx_map': 'MAPA: FORJA SOBRECARGADA',
      'tenx_sector': 'NÚCLEO REACTOR // 2X VELOCIDAD',
      'flight_title': 'VUELO JET SHINOBI',
      'flight_obj': 'Propulsores antigravedad • Esquiva redes láser',
      'flight_map': 'MAPA: AUTOPISTA ESTRATOSFÉRICA',
      'flight_sector': 'SECTOR SKY-07 // VECTOR DE VUELO',
      'threat_lvl_3': 'AMENAZA: NIVEL 3 // MEDIO',
      'threat_lvl_5': 'AMENAZA: NIVEL 5 // LETAL',
      'threat_lvl_4': 'AMENAZA: NIVEL 4 // ELEVADO',
      'hazards_label': 'PELIGROS:',
      'best_record': 'MEJOR RÉCORD:',
      'equip': 'EQUIPAR',
      'equipped': 'EQUIPADO',
      'buy': 'COMPRAR',
      'locked': 'BLOQUEADO',
      'tab_operatives': 'OPERATIVOS',
      'tab_drones': 'DRONES SHINOBI',
      'tab_boosters': 'POTENCIADORES',
      'tactical_pause': 'PAUSA TÁCTICA',
      'sys_frozen': 'ESTADO_SISTEMA // CONGELADO',
      'resume': 'REANUDAR MISIÓN',
      'restart': 'REINICIAR SECTOR',
      'abort': 'ABORTAR MISIÓN',
      'mission_failed': 'MISIÓN FALLIDA',
      'distance_reached': 'DISTANCIA ALCANZADA',
      'cp_harvested': 'CP OBTENIDO',
      'deploy_again': 'DESPLEGAR DE NUEVO',
      'exit_hub': 'VOLVER AL MENÚ',
    },

    // 4. Japanese
    'ja': {
      'game_title_cyber': 'サイバー',
      'game_title_runner': 'ニンジャ',
      'game_protocol': '影と鋼 // プロトコル V2.5',
      'active_operative': '作戦エージェント // シャドウ・シノビ',
      'deployed': '配備完了',
      'settings': '設定',
      'audio_settings': 'オーディオ設定',
      'music_volume': 'BGM音量',
      'sfx_volume': '効果音 (SFX)',
      'control_preferences': '操作環境設定',
      'control_scheme': '操作方式',
      'virtual_buttons': '仮想ボタン',
      'swipe_gestures': 'スワイプ操作',
      'swipe_sensitivity': 'スワイプ感度',
      'language': '言語 (LANGUAGE)',
      'app_language': 'アプリの言語',
      'reset_data': 'データと進行度のリセット',
      'reset_warning': 'スキン、ハイスコア、全統計データが初期化されます。',
      'reset_button': '全データを初期化',
      'daily_crate': 'デイリークレート',
      'daily_claimed': '本日の報酬受取済！次回まで：',
      'daily_available': 'デイリー報酬獲得: +150 CP!',
      'arsenal_hangar': '武器庫 ＆ 格納庫',
      'hall_of_fame': '殿堂入り',
      'global_rankings': '世界シャドウ部隊 // エリートエージェント',
      'rank': '順位',
      'operative': 'エージェント',
      'sector_record': 'セクター記録',
      'trophies': 'トロフィー',
      'core_campaign': 'メイン作戦',
      'extreme_risk': '超危険作戦',
      'aerial_zero_g': '無重力飛行',
      'endless_title': 'エンドレス・オーバードライブ',
      'endless_obj': '深層マトリックスで生存し敵メカを撃破せよ',
      'endless_map': '作戦区域: ネオトーキョー・マトリックス',
      'endless_sector': 'セクター 01-05 (200m毎変化)',
      'tenx_title': '10X ハイパーラン',
      'tenx_obj': '超高速の極限サバイバル＆10倍報酬',
      'tenx_map': '作戦区域: 過負荷リアクター',
      'tenx_sector': '炉心部 // 2倍加速',
      'flight_title': 'ジェット・シノビ・フライト',
      'flight_obj': '反重力推進 • レーザー網を回避せよ',
      'flight_map': '作戦区域: 成層圏スカイウェイ',
      'flight_sector': 'セクター SKY-07 // 航空ベクトル',
      'threat_lvl_3': '脅威度: LVL 3 // 中程度',
      'threat_lvl_5': '脅威度: LVL 5 // 致死',
      'threat_lvl_4': '脅威度: LVL 4 // 高度',
      'hazards_label': '危険要素:',
      'best_record': '最高記録:',
      'equip': '装備する',
      'equipped': '装備中',
      'buy': '購入',
      'locked': 'ロック',
      'tab_operatives': 'エージェント',
      'tab_drones': '忍ドローン',
      'tab_boosters': 'ブースター',
      'tactical_pause': '戦術一時停止',
      'sys_frozen': 'システム状態 // 停止中',
      'resume': '作戦再開',
      'restart': 'セクター再起動',
      'abort': '作戦中止',
      'mission_failed': '作戦失敗',
      'distance_reached': '到達距離',
      'cp_harvested': '獲得CP',
      'deploy_again': '再出撃',
      'exit_hub': '基地へ帰還',
    },

    // 5. French
    'fr': {
      'game_title_cyber': 'CYBER',
      'game_title_runner': 'NINJA',
      'game_protocol': 'OMBRE & ACIER // PROTOCOLE V2.5',
      'active_operative': 'AGENT ACTIF // SHINOBI DE L\'OMBRE',
      'deployed': 'DÉPLOYÉ',
      'settings': 'PARAMÈTRES',
      'audio_settings': 'PARAMÈTRES AUDIO',
      'music_volume': 'Volume Musique',
      'sfx_volume': 'Volume Effets (SFX)',
      'control_preferences': 'PRÉFÉRENCES DE CONTRÔLE',
      'control_scheme': 'Mode de Contrôle',
      'virtual_buttons': 'Boutons Virtuels',
      'swipe_gestures': 'Balayage Tactile',
      'swipe_sensitivity': 'Sensibilité du Balayage',
      'language': 'LANGUE',
      'app_language': 'Langue de l\'application',
      'reset_data': 'RÉINITIALISER LES DONNÉES',
      'reset_warning':
          'Cela effacera tous vos skins débloqués, scores et statistiques.',
      'reset_button': 'TOUT RÉINITIALISER',
      'daily_crate': 'CAISSE DU JOUR',
      'daily_claimed': 'Réclamé aujourd\'hui ! Prochain dans',
      'daily_available': 'Récompense obtenue : +150 CP !',
      'arsenal_hangar': 'ARSENAL & HANGAR',
      'hall_of_fame': 'PANTHÉON',
      'global_rankings': 'DIVISION DE L\'OMBRE MONDIALE // ÉLITE',
      'rank': 'RANG',
      'operative': 'AGENT',
      'sector_record': 'RECORD DE SECTEUR',
      'trophies': 'TROPHÉES',
      'core_campaign': 'CAMPAGNE CENTRALE',
      'extreme_risk': 'RISQUE EXTRÊME',
      'aerial_zero_g': 'VOL ZÉRO-G',
      'endless_title': 'OVERDRIVE INFINI',
      'endless_obj': 'Survivez aux secteurs matriciels et abattez les méchas',
      'endless_map': 'CARTE : MATRICE NÉO-TOKYO',
      'endless_sector': 'SECTEUR 01-05 (CYCLE DE 200M)',
      'tenx_title': 'COURSE HYPER 10X',
      'tenx_obj': 'Survie à hypervitesse et récompenses 10x',
      'tenx_map': 'CARTE : FORGE SURCHARGÉE',
      'tenx_sector': 'CŒUR DU RÉACTEUR // VITESSE 2X',
      'flight_title': 'VOL JET SHINOBI',
      'flight_obj': 'Propulseurs anti-gravité • Évitez les toiles laser',
      'flight_map': 'CARTE : VOIE STRATOSPHÉRIQUE',
      'flight_sector': 'SECTEUR SKY-07 // VECTEUR DE VOL',
      'threat_lvl_3': 'MENACE : NIVEAU 3 // MOYEN',
      'threat_lvl_5': 'MENACE : NIVEAU 5 // MORTEL',
      'threat_lvl_4': 'MENACE : NIVEAU 4 // ÉLEVÉ',
      'hazards_label': 'DANGERS :',
      'best_record': 'MEILLEUR SCORE :',
      'equip': 'ÉQUIPER',
      'equipped': 'ÉQUIPÉ',
      'buy': 'ACHETER',
      'locked': 'VERROUILLÉ',
      'tab_operatives': 'AGENTS',
      'tab_drones': 'DRONES SHINOBI',
      'tab_boosters': 'BOOSTERS',
      'tactical_pause': 'PAUSE TACTIQUE',
      'sys_frozen': 'ÉTAT_SYSTÈME // GELÉ',
      'resume': 'REPRENDRE LA MISSION',
      'restart': 'REDÉMARRER SECTEUR',
      'abort': 'ABANDONNER MISSION',
      'mission_failed': 'MISSION ÉCHOUÉE',
      'distance_reached': 'DISTANCE ATTEINTE',
      'cp_harvested': 'CP RÉCOLTÉS',
      'deploy_again': 'REDÉPLOYER',
      'exit_hub': 'RETOUR AU HUB',
    },

    // 6. German
    'de': {
      'game_title_cyber': 'CYBER',
      'game_title_runner': 'NINJA',
      'game_protocol': 'SCHATTEN & STAHL // PROTOKOLL V2.5',
      'active_operative': 'AKTIVER AGENT // SCHATTEN-SHINOBI',
      'deployed': 'EINGESETZT',
      'settings': 'EINSTELLUNGEN',
      'audio_settings': 'AUDIO-EINSTELLUNGEN',
      'music_volume': 'Musiklautstärke',
      'sfx_volume': 'Soundeffekte (SFX)',
      'control_preferences': 'STEUERUNGSEINSTELLUNGEN',
      'control_scheme': 'Steuerungsmodus',
      'virtual_buttons': 'Virtuelle Tasten',
      'swipe_gestures': 'Wischgesten',
      'swipe_sensitivity': 'Wischempfindlichkeit',
      'language': 'SPRACHE',
      'app_language': 'App-Sprache',
      'reset_data': 'DATEN ZURÜCKSETZEN',
      'reset_warning':
          'Dadurch werden alle freigeschalteten Skins und Rekorde gelöscht.',
      'reset_button': 'ALLE DATEN LÖSCHEN',
      'daily_crate': 'TÄGLICHE KISTE',
      'daily_claimed': 'Heute abgeholt! Nächste in',
      'daily_available': 'Tägliche Belohnung erhalten: +150 CP!',
      'arsenal_hangar': 'ARSENAL & HANGAR',
      'hall_of_fame': 'RUHMESHALLE',
      'global_rankings': 'GLOBALE SCHATTENDIVISION // ELITE',
      'rank': 'RANG',
      'operative': 'AGENT',
      'sector_record': 'SEKTOR-REKORD',
      'trophies': 'TROPHÄEN',
      'core_campaign': 'HAUPTKAMPAGNE',
      'extreme_risk': 'EXTREMES RISIKO',
      'aerial_zero_g': 'ZERO-G FLUG',
      'endless_title': 'ENDLOS-OVERDRIVE',
      'endless_obj': 'Überlebe tiefe Matrix-Sektoren und besiege Mechs',
      'endless_map': 'KARTE: NEO-TOKYO MATRIX',
      'endless_sector': 'SEKTOR 01-05 (200M ZYKLUS)',
      'tenx_title': '10X HYPER RUN',
      'tenx_obj': 'Hyperspeed-Überleben mit 10-fachen Belohnungen',
      'tenx_map': 'KARTE: ÜBERLADENE SCHMIEDE',
      'tenx_sector': 'REAKTORKERN // 2X GESCHWINDIGKEIT',
      'flight_title': 'JET SHINOBI FLUG',
      'flight_obj': 'Anti-Gravitationsdüsen • Weiche Lasernetzen aus',
      'flight_map': 'KARTE: STRATOSPHÄREN-SKYWAY',
      'flight_sector': 'SEKTOR SKY-07 // FLUGVEKTOR',
      'threat_lvl_3': 'BEDROHUNG: STUFE 3 // MITTEL',
      'threat_lvl_5': 'BEDROHUNG: STUFE 5 // TÖDLICH',
      'threat_lvl_4': 'BEDROHUNG: STUFE 4 // ERHÖHT',
      'hazards_label': 'GEFAHREN:',
      'best_record': 'BESTER REKORD:',
      'equip': 'AUSRÜSTEN',
      'equipped': 'AUSGERÜSTET',
      'buy': 'KAUFEN',
      'locked': 'GESPERRT',
      'tab_operatives': 'AGENTEN',
      'tab_drones': 'SHINOBI-DROHNEN',
      'tab_boosters': 'BOOSTER',
      'tactical_pause': 'TAKTIK-PAUSE',
      'sys_frozen': 'SYSTEMSTATUS // EINGEFROREN',
      'resume': 'MISSION FORTSETZEN',
      'restart': 'SEKTOR NEUSTARTEN',
      'abort': 'MISSION ABBRECHEN',
      'mission_failed': 'MISSION FEHLGESCHLAGEN',
      'distance_reached': 'ERREICHTE DISTANZ',
      'cp_harvested': 'GESAMMELTE CP',
      'deploy_again': 'ERNEUT STARTEN',
      'exit_hub': 'ZURÜCK ZUM HAUPTMENÜ',
    },

    // 7. Russian
    'ru': {
      'game_title_cyber': 'КИБЕР',
      'game_title_runner': 'НИНДЗЯ',
      'game_protocol': 'ТЕНЬ И СТАЛЬ // ПРОТОКОЛ V2.5',
      'active_operative': 'АКТИВНЫЙ АГЕНТ // ТЕНЕВОЙ СИНОБИ',
      'deployed': 'В СТРОЮ',
      'settings': 'НАСТРОЙКИ',
      'audio_settings': 'НАСТРОЙКИ ЗВУКА',
      'music_volume': 'Громкость музыки',
      'sfx_volume': 'Звуковые эффекты (SFX)',
      'control_preferences': 'ПАРАМЕТРЫ УПРАВЛЕНИЯ',
      'control_scheme': 'Схема управления',
      'virtual_buttons': 'Экранные кнопки',
      'swipe_gestures': 'Жесты смахивания',
      'swipe_sensitivity': 'Чувствительность смахивания',
      'language': 'ЯЗЫК',
      'app_language': 'Язык приложения',
      'reset_data': 'СБРОС ДАННЫХ И ПРОГРЕССА',
      'reset_warning': 'Это действие сбросит все скины, рекорды и статистику.',
      'reset_button': 'СБРОСИТЬ ВСЕ ДАННЫЕ',
      'daily_crate': 'ДНЕВНОЙ ЯЩИК',
      'daily_claimed': 'Получено сегодня! Следующий через',
      'daily_available': 'Ежедневная награда: +150 CP!',
      'arsenal_hangar': 'АРСЕНАЛ И АНГАР',
      'hall_of_fame': 'ЗАЛ СЛАВЫ',
      'global_rankings': 'ГЛОБАЛЬНЫЙ ТЕНЕВОЙ ДИВИЗИОН // ЭЛИТА',
      'rank': 'РАНГ',
      'operative': 'АГЕНТ',
      'sector_record': 'РЕКОРД СЕКТОРА',
      'trophies': 'ТРОФЕИ',
      'core_campaign': 'ОСНОВНАЯ КАМПАНИЯ',
      'extreme_risk': 'ЭКСТРЕМАЛЬНЫЙ РИСК',
      'aerial_zero_g': 'ПОЛЕТ В НЕВЕСОМОСТИ',
      'endless_title': 'БЕСКОНЕЧНЫЙ ОВЕРДРАЙВ',
      'endless_obj': 'Выживайте в матрице и уничтожайте боевых мехов',
      'endless_map': 'КАРТА: МАТРИЦА НЕО-ТОКИО',
      'endless_sector': 'СЕКТОР 01-05 (СМЕНА КАЖДЫЕ 200М)',
      'tenx_title': '10X ГИПЕР-ЗАБЕГ',
      'tenx_obj': 'Сверхскоростной забег с 10-кратной наградой CP',
      'tenx_map': 'КАРТА: ПЕРЕГРУЖЕННАЯ КУЗНИЦА',
      'tenx_sector': 'АКТИВНАЯ ЗОНА // 2X СКОРОСТЬ',
      'flight_title': 'ПОЛЕТ ДЖЕТ-СИНОБИ',
      'flight_obj': 'Антиграв-двигатели • Уклоняйтесь от лазерных сетей',
      'flight_map': 'КАРТА: СТРАТОСФЕРНЫЙ ПУТЬ',
      'flight_sector': 'СЕКТОР SKY-07 // ВЕКТОР ПОЛЕТА',
      'threat_lvl_3': 'УГРОЗА: УР. 3 // СРЕДНЯЯ',
      'threat_lvl_5': 'УГРОЗА: УР. 5 // СМЕРТЕЛЬНАЯ',
      'threat_lvl_4': 'УГРОЗА: УР. 4 // ПОВЫШЕННАЯ',
      'hazards_label': 'ОПАСНОСТИ:',
      'best_record': 'ЛУЧШИЙ РЕКОРД:',
      'equip': 'ВЫБРАТЬ',
      'equipped': 'ВЫБРАНО',
      'buy': 'КУПИТЬ',
      'locked': 'ЗАКРЫТО',
      'tab_operatives': 'АГЕНТЫ',
      'tab_drones': 'СИНОБИ-ДРОНЫ',
      'tab_boosters': 'БУСТЕРЫ',
      'tactical_pause': 'ТАКТИЧЕСКАЯ ПАУЗА',
      'sys_frozen': 'СТАТУС_СИСТЕМЫ // ЗАМОРОЖЕНО',
      'resume': 'ПРОДОЛЖИТЬ МИССИЮ',
      'restart': 'ПЕРЕЗАПУСК СЕКТОРА',
      'abort': 'ПРЕРВАТЬ МИССИЮ',
      'mission_failed': 'МИССИЯ ПРОВАЛЕНА',
      'distance_reached': 'ПРОЙДЕННОЕ РАССТОЯНИЕ',
      'cp_harvested': 'СОБРАНО CP',
      'deploy_again': 'В БОЙ СНОВА',
      'exit_hub': 'ВЫХОД В МЕНЮ',
    },

    // 8. Chinese (Simplified)
    'zh': {
      'game_title_cyber': '赛博',
      'game_title_runner': '忍者',
      'game_protocol': '暗影与钢铁 // 协议 V2.5',
      'active_operative': '当前特工 // 暗影忍者',
      'deployed': '已部署',
      'settings': '设置',
      'audio_settings': '音频设置',
      'music_volume': '音乐音量',
      'sfx_volume': '音效音量 (SFX)',
      'control_preferences': '控制偏好',
      'control_scheme': '控制方案',
      'virtual_buttons': '虚拟按键',
      'swipe_gestures': '滑动手势',
      'swipe_sensitivity': '滑动灵敏度',
      'language': '语言',
      'app_language': '应用语言',
      'reset_data': '重置数据与进度',
      'reset_warning': '这将重置所有已解锁皮肤、最高纪录与统计数据。',
      'reset_button': '重置全部数据',
      'daily_crate': '每日补给箱',
      'daily_claimed': '今日已领取！下次领取：',
      'daily_available': '每日奖励领取成功：+150 CP！',
      'arsenal_hangar': '军械库与机库',
      'hall_of_fame': '名人堂',
      'global_rankings': '全球暗影部队 // 精英特工',
      'rank': '排名',
      'operative': '特工',
      'sector_record': '区域纪录',
      'trophies': '奖杯',
      'core_campaign': '核心战役',
      'extreme_risk': '极度危险',
      'aerial_zero_g': '零重力飞行',
      'endless_title': '无尽超频',
      'endless_obj': '在矩阵深层存活并摧毁机械巨兽',
      'endless_map': '地图：新东京矩阵',
      'endless_sector': '区域 01-05（每200米切换）',
      'tenx_title': '10倍极速奔跑',
      'tenx_obj': '超高速生死存亡与10倍CP狂暴奖励',
      'tenx_map': '地图：超压铸造厂',
      'tenx_sector': '反应堆核心 // 2倍急速',
      'flight_title': '喷气忍者飞行',
      'flight_obj': '反重力推进器 • 躲避激光网',
      'flight_map': '地图：平流层空中走廊',
      'flight_sector': '区域 SKY-07 // 飞行矢量',
      'threat_lvl_3': '威胁等级：LVL 3 // 中等',
      'threat_lvl_5': '威胁等级：LVL 5 // 致命',
      'threat_lvl_4': '威胁等级：LVL 4 // 警戒',
      'hazards_label': '危险物：',
      'best_record': '最高纪录：',
      'equip': '装备',
      'equipped': '已装备',
      'buy': '购买',
      'locked': '已锁定',
      'tab_operatives': '特工角色',
      'tab_drones': '忍者无人机',
      'tab_boosters': '强化道具',
      'tactical_pause': '战术暂停',
      'sys_frozen': '系统状态 // 已冻结',
      'resume': '继续任务',
      'restart': '重置区域',
      'abort': '终止任务',
      'mission_failed': '任务失败',
      'distance_reached': '抵达距离',
      'cp_harvested': '获得CP',
      'deploy_again': '再次出击',
      'exit_hub': '返回主界面',
    },

    // 9. Portuguese
    'pt': {
      'game_title_cyber': 'CYBER',
      'game_title_runner': 'NINJA',
      'game_protocol': 'SOMBRA E AÇO // PROTOCOLO V2.5',
      'active_operative': 'OPERATIVO ATIVO // SHINOBI SOMBRA',
      'deployed': 'EM CAMPO',
      'settings': 'CONFIGURAÇÕES',
      'audio_settings': 'ÁUDIO',
      'music_volume': 'Volume da Música',
      'sfx_volume': 'Efeitos Sonoros (SFX)',
      'control_preferences': 'CONTROLES',
      'control_scheme': 'Modo de Controle',
      'virtual_buttons': 'Botões Virtuais',
      'swipe_gestures': 'Gestos de Deslize',
      'swipe_sensitivity': 'Sensibilidade do Deslize',
      'language': 'IDIOMA',
      'app_language': 'Idioma do Jogo',
      'reset_data': 'RESETAR DADOS E PROGRESSO',
      'reset_warning':
          'Isso irá reiniciar todos os trajes, recordes e estatísticas.',
      'reset_button': 'RESETAR TODOS OS DADOS',
      'daily_crate': 'CAIXA DIÁRIA',
      'daily_claimed': 'Coletado hoje! Próxima em',
      'daily_available': 'Recompensa diária coletada: +150 CP!',
      'arsenal_hangar': 'ARSENAL E HANGAR',
      'hall_of_fame': 'HALL DA FAMA',
      'global_rankings': 'DIVISÃO SOMBRA GLOBAL // AGENTES DE ELITE',
      'rank': 'RANK',
      'operative': 'AGENTE',
      'sector_record': 'RECORDE DO SETOR',
      'trophies': 'TROFÉUS',
      'core_campaign': 'CAMPANHA PRINCIPAL',
      'extreme_risk': 'RISCO EXTREMO',
      'aerial_zero_g': 'VOO ZERO-G',
      'endless_title': 'OVERDRIVE INFINITO',
      'endless_obj': 'Sobreviva aos setores da matriz e derrote mechas',
      'endless_map': 'MAPA: MATRIZ NEO-TÓQUIO',
      'endless_sector': 'SETOR 01-05 (CICLO DE 200M)',
      'tenx_title': 'CORRIDA HIPER 10X',
      'tenx_obj': 'Sobrevivência em hipervelocidade com 10x recompensas',
      'tenx_map': 'MAPA: FORJA SOBRECARREGADA',
      'tenx_sector': 'NÚCLEO DO REATOR // VELOCIDADE 2X',
      'flight_title': 'VOO JET SHINOBI',
      'flight_obj': 'Propulsores antigravidade • Desvie de redes laser',
      'flight_map': 'MAPA: AUTOESTRADA ESTRATOSFÉRICA',
      'flight_sector': 'SETOR SKY-07 // VETOR DE VOO',
      'threat_lvl_3': 'AMEAÇA: NÍVEL 3 // MÉDIA',
      'threat_lvl_5': 'AMEAÇA: NÍVEL 5 // LETAL',
      'threat_lvl_4': 'AMEAÇA: NÍVEL 4 // ELEVADA',
      'hazards_label': 'PERIGOS:',
      'best_record': 'MELHOR RECORDE:',
      'equip': 'EQUIPAR',
      'equipped': 'EQUIPADO',
      'buy': 'COMPRAR',
      'locked': 'BLOQUEADO',
      'tab_operatives': 'AGENTES',
      'tab_drones': 'DRONES SHINOBI',
      'tab_boosters': 'BOOSTERS',
      'tactical_pause': 'PAUSA TÁTICA',
      'sys_frozen': 'ESTADO_DO_SISTEMA // CONGELADO',
      'resume': 'RETOMAR MISSÃO',
      'restart': 'REINICIAR SETOR',
      'abort': 'ABORTAR MISSÃO',
      'mission_failed': 'MISSÃO FALHOU',
      'distance_reached': 'DISTÂNCIA ALCANÇADA',
      'cp_harvested': 'CP COLETADO',
      'deploy_again': 'JOGAR NOVAMENTE',
      'exit_hub': 'VOLTAR AO MENU',
    },

    // 10. Arabic
    'ar': {
      'game_title_cyber': 'سايبر',
      'game_title_runner': 'نينجا',
      'game_protocol': 'الظل والصلب // بروتوكول V2.5',
      'active_operative': 'العميل النشط // شينوبي الظل',
      'deployed': 'تم النشر',
      'settings': 'الإعدادات',
      'audio_settings': 'إعدادات الصوت',
      'music_volume': 'مستوى الموسيقى',
      'sfx_volume': 'المؤثرات الصوتية (SFX)',
      'control_preferences': 'تفضيلات التحكم',
      'control_scheme': 'نمط التحكم',
      'virtual_buttons': 'أزرار افتراضية',
      'swipe_gestures': 'إيماءات السحب',
      'swipe_sensitivity': 'حساسية السحب',
      'language': 'اللغة',
      'app_language': 'لغة اللعبة',
      'reset_data': 'إعادة ضبط البيانات والتقدم',
      'reset_warning':
          'سيؤدي هذا إلى إعادة تعيين جميع الأزياء والأرقام القياسية والإحصائيات.',
      'reset_button': 'إعادة تعيين الكل',
      'daily_crate': 'الصندوق اليومي',
      'daily_claimed': 'تمت المطالبة اليوم! التالي في',
      'daily_available': 'تم استلام المكافأة اليومية: +150 CP!',
      'arsenal_hangar': 'الترسانة والحظيرة',
      'hall_of_fame': 'قاعة المشاهير',
      'global_rankings': 'قسم الظل العالمي // نخبة العملاء',
      'rank': 'الرتبة',
      'operative': 'العميل',
      'sector_record': 'رقم القطاع',
      'trophies': 'الكؤوس',
      'core_campaign': 'الحملة الرئيسية',
      'extreme_risk': 'خطر أقصى',
      'aerial_zero_g': 'طيران انعدام الجاذبية',
      'endless_title': 'أوفردرايف لا نهائي',
      'endless_obj': 'البقاء على قيد الحياة في المصفوفة وهزيمة الآليات',
      'endless_map': 'الخريطة: مصفوفة نيو-طوكيو',
      'endless_sector': 'القطاع 01-05 (دورة كل 200 متر)',
      'tenx_title': 'ركض فائق 10X',
      'tenx_obj': 'سرعة فائقة ومكافآت مضاعفة 10x من CP',
      'tenx_map': 'الخريطة: مصنع الشحن الزائد',
      'tenx_sector': 'قلب المفاعل // سرعة مضاعفة 2X',
      'flight_title': 'طيران نفاث شينوبي',
      'flight_obj': 'دفع مضاد للجاذبية • تفادي شبكات الليزر',
      'flight_map': 'الخريطة: الممر الجوي للستراتوسفير',
      'flight_sector': 'القطاع SKY-07 // ناقل الطيران',
      'threat_lvl_3': 'مستوى التهديد: 3 // متوسط',
      'threat_lvl_5': 'مستوى التهديد: 5 // مميت',
      'threat_lvl_4': 'مستوى التهديد: 4 // مرتفع',
      'hazards_label': 'الأخطار:',
      'best_record': 'أفضل رقم قياسي:',
      'equip': 'تجهيز',
      'equipped': 'مُجهّز',
      'buy': 'شراء',
      'locked': 'مُقفل',
      'tab_operatives': 'العملاء',
      'tab_drones': 'طائرات شينوبي',
      'tab_boosters': 'المعززات',
      'tactical_pause': 'إيقاف تكتيكي',
      'sys_frozen': 'حالة النظام // مجمد',
      'resume': 'استئناف المهمة',
      'restart': 'إعادة تشغيل القطاع',
      'abort': 'إلغاء المهمة',
      'mission_failed': 'فشلت المهمة',
      'distance_reached': 'المسافة المقطوعة',
      'cp_harvested': 'النقاط المحصودة CP',
      'deploy_again': 'إعادة النشر',
      'exit_hub': 'العودة للرئيسية',
    },

    // 11. Korean
    'ko': {
      'game_title_cyber': '사이버',
      'game_title_runner': '닌자',
      'game_protocol': '그림자와 강철 // 프로토콜 V2.5',
      'active_operative': '작전 요원 // 섀도우 시노비',
      'deployed': '출격 완료',
      'settings': '설정',
      'audio_settings': '오디오 설정',
      'music_volume': '배경음 볼륨',
      'sfx_volume': '효과음 (SFX)',
      'control_preferences': '조작 환경 설정',
      'control_scheme': '조작 방식',
      'virtual_buttons': '가상 버튼',
      'swipe_gestures': '스와이프 제스처',
      'swipe_sensitivity': '스와이프 감도',
      'language': '언어',
      'app_language': '게임 언어',
      'reset_data': '데이터 및 진행도 초기화',
      'reset_warning': '모든 스킨, 최고 기록 및 통계 데이터가 초기화됩니다.',
      'reset_button': '모든 데이터 초기화',
      'daily_crate': '일일 보급 상자',
      'daily_claimed': '오늘 수령 완료! 다음 보급까지:',
      'daily_available': '일일 보상 획득: +150 CP!',
      'arsenal_hangar': '무기고 및 격납고',
      'hall_of_fame': '명예의 전당',
      'global_rankings': '글로벌 섀도우 사단 // 엘리트 요원',
      'rank': '순위',
      'operative': '요원',
      'sector_record': '섹터 최고 기록',
      'trophies': '트로피',
      'core_campaign': '핵심 작전',
      'extreme_risk': '초고위험 작전',
      'aerial_zero_g': '무중력 비행',
      'endless_title': '엔드리스 오버드라이브',
      'endless_obj': '심층 매트릭스에서 생존하고 적 메카를 처치하세요',
      'endless_map': '작전 지도: 네오 도쿄 매트릭스',
      'endless_sector': '섹터 01-05 (200M 주기 변환)',
      'tenx_title': '10X 하이퍼 런',
      'tenx_obj': '초고속 생존과 10배 CP 보상',
      'tenx_map': '작전 지도: 과충전 포지',
      'tenx_sector': '원자로 코어 // 2배 가속',
      'flight_title': '제트 시노비 플라이트',
      'flight_obj': '반중력 추진기 • 레이저 웹 회피',
      'flight_map': '작전 지도: 성층권 스카이웨이',
      'flight_sector': '섹터 SKY-07 // 비행 벡터',
      'threat_lvl_3': '위협 등급: LVL 3 // 보통',
      'threat_lvl_5': '위협 등급: LVL 5 // 치명적',
      'threat_lvl_4': '위협 등급: LVL 4 // 경계',
      'hazards_label': '위험 요소:',
      'best_record': '최고 기록:',
      'equip': '장착',
      'equipped': '장착됨',
      'buy': '구매',
      'locked': '잠김',
      'tab_operatives': '요원',
      'tab_drones': '시노비 드론',
      'tab_boosters': '부스터',
      'tactical_pause': '작전 일시 정지',
      'sys_frozen': '시스템 상태 // 정지됨',
      'resume': '작전 재개',
      'restart': '섹터 재시작',
      'abort': '작전 중단',
      'mission_failed': '작전 실패',
      'distance_reached': '도달 거리',
      'cp_harvested': '획득한 CP',
      'deploy_again': '다시 출격',
      'exit_hub': '메인 메뉴로 이동',
    },

    // 12. Italian
    'it': {
      'game_title_cyber': 'CYBER',
      'game_title_runner': 'NINJA',
      'game_protocol': 'OMBRA E ACCIAIO // PROTOCOLLO V2.5',
      'active_operative': 'OPERATIVO ATTIVO // SHINOBI OMBRA',
      'deployed': 'SCHIERATO',
      'settings': 'IMPOSTAZIONI',
      'audio_settings': 'IMPOSTAZIONI AUDIO',
      'music_volume': 'Volume Musica',
      'sfx_volume': 'Effetti Sonori (SFX)',
      'control_preferences': 'PREFERENZE DI CONTROLLO',
      'control_scheme': 'Modalità di Controllo',
      'virtual_buttons': 'Pulsanti Virtuali',
      'swipe_gestures': 'Gesti di Scorrimento',
      'swipe_sensitivity': 'Sensibilità Scorrimento',
      'language': 'LINGUA',
      'app_language': 'Lingua del Gioco',
      'reset_data': 'RESETTA DATI E PROGRESSI',
      'reset_warning':
          'Questo resetterà tutte le skin sbloccate, record e statistiche.',
      'reset_button': 'RESETTA TUTTI I DATI',
      'daily_crate': 'CASSA GIORNALIERA',
      'daily_claimed': 'Riscattato oggi! Prossimo tra',
      'daily_available': 'Ricompensa giornaliera riscossa: +150 CP!',
      'arsenal_hangar': 'ARSENALE E HANGAR',
      'hall_of_fame': 'SALA DELLA GLORIA',
      'global_rankings': 'DIVISIONE OMBRA GLOBALE // AGENTI D\'ÉLITE',
      'rank': 'RANGO',
      'operative': 'AGENTE',
      'sector_record': 'RECORD SETTORE',
      'trophies': 'TROFEI',
      'core_campaign': 'CAMPAGNA PRINCIPALE',
      'extreme_risk': 'RISCHIO ESTREMO',
      'aerial_zero_g': 'VOLO ZERO-G',
      'endless_title': 'OVERDRIVE INFINITO',
      'endless_obj': 'Sopravvivi nei settori della matrice e abbatti i mecha',
      'endless_map': 'MAPPA: MATRICE NEO-TOKYO',
      'endless_sector': 'SETTORE 01-05 (CICLO DI 200M)',
      'tenx_title': 'CORSA IPER 10X',
      'tenx_obj': 'Sopravvivenza a iper-velocità e ricompense 10x CP',
      'tenx_map': 'MAPPA: FUCINA SOVRACCARICATA',
      'tenx_sector': 'NUCLEO DEL REATTORE // VELOCITÀ 2X',
      'flight_title': 'VOLO JET SHINOBI',
      'flight_obj': 'Propulsori anti-gravità • Evita ragnatele laser',
      'flight_map': 'MAPPA: AUTOSTRADA STRATOSFERICA',
      'flight_sector': 'SETTORE SKY-07 // VETTORE DI VOLO',
      'threat_lvl_3': 'MINACCIA: LIVELLO 3 // MEDIO',
      'threat_lvl_5': 'MINACCIA: LIVELLO 5 // LETALE',
      'threat_lvl_4': 'MINACCIA: LIVELLO 4 // ELEVATO',
      'hazards_label': 'PERICOLI:',
      'best_record': 'MIGLIOR RECORD:',
      'equip': 'EQUIPAGGIA',
      'equipped': 'EQUIPAGGIATO',
      'buy': 'ACQUISTA',
      'locked': 'BLOCCATO',
      'tab_operatives': 'AGENTI',
      'tab_drones': 'DRONI SHINOBI',
      'tab_boosters': 'BOOSTER',
      'tactical_pause': 'PAUSA TATTICA',
      'sys_frozen': 'STATO_SISTEMA // CONGELATO',
      'resume': 'RIPRENDI MISSIONE',
      'restart': 'RIAVVIA SETTORE',
      'abort': 'INTERROMPI MISSIONE',
      'mission_failed': 'MISSIONE FALLITA',
      'distance_reached': 'DISTANZA RAGGIUNTA',
      'cp_harvested': 'CP RACCOLTI',
      'deploy_again': 'SCHIERATI ANCORA',
      'exit_hub': 'TORNA AL MENU',
    },
  };

  String tr(String key) {
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

extension LocalizationExtension on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
